% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  12pt,
  leqno]{article}
\usepackage{xcolor}
\usepackage[margin = 1.5cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[]{natbib}
\bibliographystyle{unsrtnat}
\usepackage{xcolor, color, ucs}     % http://ctan.org/pkg/xcolor
\usepackage{natbib}
\setcitestyle{authoryear,round}
\usepackage{booktabs}          % package for thick lines in tables
\usepackage{amsfonts,amsthm,amsmath}          % AMS Fonts
\usepackage{mathtools}
\usepackage{graphicx}          % Insert .pdf, .eps or .png
\usepackage{enumitem}          % http://ctan.org/pkg/enumitem
\usepackage{tabularx}          % Get scale boxes for tables
\usepackage{float}             % Force floats around
\usepackage{placeins}          % For use of \FloatBarrier 
\usepackage{rotating}          % Rotate long tables horizontally
\usepackage{bbm}               
\usepackage{bm}                
\usepackage{csquotes}           % \enquote{} and \textquote[][]{} environments
\usepackage{subfigure}
\usepackage{array}

\usepackage{longtable}


\setlist{nosep}

\usepackage{setspace}
\doublespacing



\usepackage{multirow}

\usepackage{hyperref}
\usepackage[noabbrev]{cleveref} % Should be loaded after \usepackage{hyperref}
\usepackage[small,bf]{caption}  % Captions
\captionsetup[table]{position=bottom} % force captions below tables


\parskip=8pt
\parindent=0pt
\delimitershortfall=-1pt
\interfootnotelinepenalty=100000

\newcommand{\qedknitr}{\hfill\rule{1.2ex}{1.2ex}}

%

\def\tightlist{}

\makeatletter
% align all math after the command
\newcommand{\mathleft}{\@fleqntrue\@mathmargin\parindent}
\newcommand{\mathcenter}{\@fleqnfalse}
% tilde with text over it
\newcommand{\distas}[1]{\mathbin{\overset{#1}{\kern\z@\sim}}}%
\newsavebox{\mybox}\newsavebox{\mysim}
\newcommand{\distras}[1]{%
  \savebox{\mybox}{\hbox{\kern3pt$\scriptstyle#1$\kern3pt}}%
  \savebox{\mysim}{\hbox{$\sim$}}%
  \mathbin{\overset{#1}{\kern\z@\resizebox{\wd\mybox}{\ht\mysim}{$\sim$}}}%
}
\makeatother

% \newtheoremstyle{newstyle}
% {} %Aboveskip
% {} %Below skip
% {\mdseries} %Body font e.g.\mdseries,\bfseries,\scshape,\itshape
% {} %Indent
% {\bfseries} %Head font e.g.\bfseries,\scshape,\itshape
% {.} %Punctuation afer theorem header
% { } %Space after theorem header
% {} %Heading

\newtheorem{thm}{Theorem}
\newtheorem{prop}[thm]{Proposition}
\newtheorem{lem}{Lemma}
\newtheorem{cor}{Corollary}
\newtheorem{definition}{Definition}
\newcommand*\diff{\mathop{}\!\mathrm{d}}
\newcommand*\Diff[1]{\mathop{}\!\mathrm{d^#1}}
\DeclareMathOperator{\E}{\mathrm{E}}
\DeclareMathOperator{\Var}{\mathrm{Var}}
\DeclareMathOperator{\R}{\mathbb{R}}
\DeclarePairedDelimiter\abs{\lvert}{\rvert}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Building a Design-Based Matching Pipeline: From Principles to Practical Implementation in R},
  pdfauthor={ and },
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Building a Design-Based Matching Pipeline: From Principles to
Practical Implementation in R}
\author{\href{mailto:thomas.leavitt@baruch.cuny.edu}{Thomas Leavitt} and
\href{mailto:luke_miratrix@gse.harvard.edu }{Luke W. Miratrix}}
\date{}

\begin{document}
\maketitle

\begin{abstract}
\singlespacing
\noindent Matching, a canonical design for observational studies, takes many forms that rest on distinct --- yet often implicit --- statistical principles. We construct a matching pipeline for practitioners that makes these principles explicit and integrates stages often treated separately within a coherent design-based framework. The pipeline begins from the conceptual ideal of a randomized experiment, traces how observational studies depart from it, and then employs matching to approximate that ideal. The next stage is inference under the as-if randomization assumption that matched sets are equivalent to a collection of randomized experiments within blocks, where each block has a fixed number of treated units equal to the number observed in that set. Under this assumption, we consider inference on all individual effects in the "sharp" framework and on the average effect in the "weak" framework. The final stage is a sensitivity analysis to assess, under either framework, how inferences change under departures from as-if randomization. Each step includes extensively commented \texttt{R} code that equips practitioners to implement both established and newly developed procedures, including several not yet available in existing \texttt{R} packages. We illustrate the full workflow through an application examining the effect of United Nations peacekeeping interventions on the duration of post-conflict peace.
\end{abstract}

\newpage

\section{Design-Based Foundations of the Matching
Pipeline}\label{design-based-foundations-of-the-matching-pipeline}

\subsection{The Randomized Experimental
Ideal}\label{the-randomized-experimental-ideal}

Imagine a randomized experiment in which a researcher flips a fair coin
independently for each individual in the study. Heads means assignment
of the individual to control, while tails means assignment to treatment.
After assignments to treatment and control, the researcher administers
the conditions and then compares outcomes between treated and control
groups.

Why is this procedure effective? Randomization is a \emph{fair lottery}:
Every individual has the same chance of being assigned to treatment.
This means that individuals who would respond more strongly to treatment
are no more likely to receive it than those who would respond less
strongly, and the same is true for control. Because each individual's
assignment is determined by the same coin toss (with the same
probability of landing heads or tails), randomization leaves only two
possibilities: (1) the difference in outcomes between treatment and
control groups reflects the true causal effect, or (2) chance variation
produced a misleading difference. Although misleading differences can
occur by chance, randomization is valuable because it enables us to use
statistical tools to quantify and limit the chance of such errors. As a
result, randomized experiments yield especially credible causal
conclusions.

Randomization is useful not only as a procedure, but also as an idea. It
helps us understand when statistical tools will (and will not) yield
credible conclusions, even when we have not directly randomized. In an
observational study, the researcher does not control who receives the
treatment and instead observes units after they have been assigned to
treatment and control groups. In such settings, the idea of
randomization can guide how we design studies so that they yield more
credible causal conclusions.

\subsection{Bridging Randomized Experiments and Observational
Studies}\label{bridging-randomized-experiments-and-observational-studies}

A useful framework for connecting randomized experiments to
observational studies is what \citet{rubin1977} calls ``assignment to
treatment group on the basis of a covariate,'' where a covariate is a
pre-treatment characteristic of a study's units. To make this idea
concrete, suppose treatment is assigned by independent coin tosses for
each individual in which the probability of heads or tails depends on
that individual's value of a single covariate. Consequently, all
individuals with the same covariate value share the same chance of
ending up in treatment, while those with a different covariate value
share a different chance.

In this setting, we can envision forming groups (i.e., matched sets) so
that all individuals within a group share the same covariate value. Each
group then functions as a miniature randomized experiment in that random
chance alone explains why some individuals in the group ended up in
treatment while others did not. Importantly, to justify this
interpretation, we do not need to know each individual's actual
probability of treatment. It is enough to know that the probability of
treatment depends only on the covariate, which ensures that all
individuals with the same covariate value have the same chance of
treatment.

\subsection{Matching to Approximate the Randomized Experimental
Ideal}\label{matching-to-approximate-the-randomized-experimental-ideal}

The same intuition applies to matching when the probability of treatment
depends on many baseline covariates. The underlying idea is that
individuals with similar covariates have similar treatment assignment
probabilities. Thus, in an effort to recreate a randomized experiment,
we use the covariates we observe and believe determine treatment chances
in order to divide individuals into groups, with each group containing
both treated and control subjects who are homogeneous in those
covariates. We are, in effect, constructing a new single variable: group
(i.e., matched set) membership. We can think of this membership variable
as the single covariate in the framework of ``assignment to treatment
group on the basis of a covariate'' \citep{rubin1977} discussed above.
Although we still do not know each individual's treatment probability,
the hope is that all individuals within a group share the same
probability, whatever it may be.

We call the condition in which all individuals within matched sets share
the same treatment probability \emph{as-if randomization}, although
other terms such as \emph{selection on observables} and \emph{strong
ignorability} are common. The term as-if randomization is especially
fitting: When all units within each matched set share the same
individual treatment probability, all assignments within each set ---
holding fixed the set's observed number of treated units --- are equally
likely. In this case, the probability distribution over these
assignments is equivalent to that induced by a randomized experiment in
which a researcher first forms blocks corresponding to the matched sets
and then randomly assigns a fixed number of units to treatment within
each block. Thus, when as-if randomization holds, we can apply the same
statistical tools that we would use under such a block-randomized design
to draw credible causal inferences from the observational study.

\subsection{Why Sensitivity Analysis
Matters}\label{why-sensitivity-analysis-matters}

Unlike a randomized experiment, even the best matched designs rely on
the strong assumption of as-if randomization. When this assumption
holds, we can draw causal conclusions by analyzing the data as if they
came from a randomized experiment. However, if the assumption is wrong,
our causal claims are no longer guaranteed to be credible.

How can this assumption fail? First, individuals within a group may be
similar on observed covariates, but not similar enough to have the same
treatment probabilities. Second, treatment assignment may depend on
covariates we did not measure. If so, even if individuals within groups
appear comparable on observed covariates, those individuals may still
differ on hidden covariates that determine the probability of treatment.

For these reasons, it is important to assess the sensitivity of our
causal conclusions to departures from as-if randomization. Conclusions
are especially convincing when they hold not only under this assumption,
but also under moderate violations of it. Conclusions that collapse
under only mild departures are much less convincing.

\subsection{Roadmap of the Design-Based Matching
Pipeline}\label{roadmap-of-the-design-based-matching-pipeline}

Building on these design-based foundations, we now outline a pipeline
that starts with matching and then proceeds to inference and sensitivity
analysis:

\begin{itemize}
\item
  \textbf{Construct and evaluate matched sets}. Given the specified
  covariates to be balanced, we begin with the mechanics of optimal
  matching \citep{hansen2004, hansenklopfer2006}: choosing a distance
  measure that defines similarity on the covariates, setting calipers
  --- maximum allowable distances between treated and control units for
  inclusion in the same matched set --- and imposing structural
  constraints (e.g., requiring matches to be pairs). We then show how to
  evaluate the resulting design in terms of both effective sample size
  and covariate balance. For the latter, we focus on tests proposed by
  \citet{hansenbowers2008} that compare the matched design's covariate
  balance to what one would expect under an equivalent completely
  randomized experiment within blocks (that is, random assignment with a
  fixed number of treated units per block).
\item
  \textbf{Draw causal inferences}. Once a matched design is chosen,
  practitioners can conduct inference under as-if randomization, either
  within a ``sharp'' causal framework, which pertains to
  individual-level effects for all units, or a ``weak'' framework, which
  pertains to a summary quantity of the unit-level causal effects,
  typically the average treatment effect (ATE). For the sharp framework,
  we focus on how researchers can use both simulation- and Normal-based
  approximations to the exact randomization distribution to perform
  hypothesis tests, which can be inverted to obtain confidence sets and
  point estimates. For the weak framework, we cover estimation of the
  ATE and hypothesis tests about it. We emphasize exposition and code
  for recent variance estimators tailored to designs with only \(1\)
  treated or \(1\) control unit per matched set
  \citep{fogarty2018, pashleymiratrix2021} --- an important case, since
  such designs are optimal in terms of balance and effective sample size
  \citep{gurosenbaum1993, rosenbaum1991, hansen2004}.
\item
  \textbf{Assess sensitivity}. Finally, we turn to sensitivity analyses
  under both inferential frameworks. We review established methods for
  conducting sensitivity analysis for tests of sharp nulls under
  possible violations of as-if randomization
  \citep{rosenbaumkrieger1990, gastwirthetal2000, rosenbaum2018}. We
  then describe and implement new methods that extend sensitivity
  analysis to tests of weak null hypotheses \citep{fogarty2023}.
\end{itemize}

Below we present a flow diagram summarizing the overall pipeline,
partitioned into three sections aligned with the manuscript's sections.
The diagram displays each step and decision point, the relevant
\texttt{R} tools (whether existing packages or custom functions included
herein), and core references. All relevant code and replication
materials are publicly available in the manuscript's companion
\href{https://github.com/tl2624/matching-guide}{GitHub repository}

\singlespacing
\begin{figure}[H]

{\centering \includegraphics[width=\linewidth]{fig/version_2/matching_pipeline_flowchart_V2} 

}

\caption{Flow diagram of the design-based matching pipeline.\label{fig: pipeline}}\label{fig:diagram}
\end{figure}
\doublespacing

\section{Implementation of the Matching
Pipeline}\label{implementation-of-the-matching-pipeline}

We provide a high-level overview of the ideas behind matching and
include code that demonstrates how to implement those ideas with various
\texttt{R} packages. We also work through some of these steps ``by
hand'' to underscore the underlying conceptual issues. Doing so also
gives practitioners more flexibility to adapt the matching pipeline to
their own needs.

We break the implementation into specific decision points that
practitioners commonly face, and present the pipeline in three main
stages (see \Cref{fig: pipeline}):

\textbf{First Stage: Making a Matched Dataset (toward Justifying As-If
Randomization)}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  How Do I Measure Similarity on My Chosen Covariates?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Similarity on the Estimated Propensity Score
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
  How Can I Apply Rules for Matches to Ensure Comparability?
\item
  How Can I Apply Rules for Matches to Improve Effective Sample Size?
\item
  How Do I Actually Form the Matches?
\item
  How Do I Decide Whether to Move Ahead with My Matched Design?
\end{enumerate}

\textbf{Second Stage: Causal Inference (under As-If Randomization)}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  How Do I Draw Inferences under the Sharp Framework?
\item
  How Do I Draw Inferences under the Weak Framework?
\end{enumerate}

\textbf{Third Stage: Sensitivity Analysis (Departures from As-If
Randomization)}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  How Do Inferences under the Sharp Framework Change under these
  Departures?
\end{enumerate}

\begin{itemize}
\item
  Finding the Worst-Case Scenario of Hidden Confounding for Valid
  Inference

  \begin{itemize}
  \tightlist
  \item
    Separable Approximation
  \item
    Taylor Series Approximation
  \end{itemize}
\item
  Conducting Sensitivity Analysis under the Worst-Case Scenario
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  How Do Inferences under the Weak Framework Change under these
  Departures?
\end{enumerate}

Before turning to First Stage, we introduce a running example taken from
\citet{gilligansergenti2008}, which we use throughout this manuscript.

\subsection{Running Example: United Nations Peacekeeping and
Post-Conflict
Peace}\label{running-example-united-nations-peacekeeping-and-post-conflict-peace}

We introduce matching through an example that examines the causal effect
of United Nations (UN) peacekeeping missions on the durability of
post-conflict peace, a question of central importance for both academic
research and policy. Our example draws on data from
\citet{gilligansergenti2008}, whose title includes the phrase ``Matching
to Improve Causal Inference,'' underscoring the value of applying
matching to study the UN's causal impact on post-conflict peace. These
data are publicly available in the supplementary information of the
article's webpage in the \emph{Quarterly Journal of Political Science}
(DOI:
\href{https://doi.org/10.1561/100.00007051}{10.1561/100.00007051}).

The dataset we use from \citet{gilligansergenti2008} includes 87
observations, each corresponding to a country's peace period episode
following a civil war, with episodes beginning as early as January 1989
and data extending through December 2003. In some episodes, UN
peacekeepers intervened (e.g., Sierra Leone, Jan 2001 - Dec 2003), while
in others they did not (e.g., Macedonia, Sep 2001 - Dec 2003). The
treatment variable is UN intervention (\texttt{UN}), coded as \(1\) if a
UN mission was present during the peace period and \(0\) otherwise. The
outcome variable is the duration of the peace spell, which
\citet{gilligansergenti2008} measure as the log of the number of days
from the start of peace until either the outbreak of a new conflict or
right-censoring at December 2003. This log-transformed outcome
(\texttt{ldur}) captures the total length of the peace period rather
than the time elapsed after a potential UN intervention. In practice,
however, UN interventions almost always began immediately after the
onset of peace: ``Of the 19 post-conflict UN interventions, the United
Nations was present within the first month for 16 of them''
\citep[p.~118]{gilligansergenti2008}. In what follows, we set aside
these measurement details.

As \citet{gilligansergenti2008} state, ``UN missions are not randomly
assigned'' (p.~89). Whether peacekeepers are present during a given
post-conflict peace period presumably depends on baseline covariates
measured by \citet{gilligansergenti2008}, including the logged number of
deaths (\texttt{lwdeaths}), the logged duration of the previous war
(\texttt{lwdurat}), ethnic fractionalization (\texttt{ethfrac}, a 0-100
index for which dividing by 100 is intended to represent the probability
that two randomly chosen individuals belong to different ethnic groups),
logged population size (\texttt{pop}) and others. We implement matching
using these same covariates, but emphasize that our exercise is
expository and not intended as a replication of the original findings.

\subsubsection{Loading the Data for the Running
Example}\label{loading-the-data-for-the-running-example}

To load the data, you could first download the replication files from
the supplementary information on the article's webpage (DOI:
\href{https://doi.org/10.1561/100.00007051}{10.1561/100.00007051}), save
the files to your working directory, and then use a package such as
\texttt{haven} to load the Stata (.dta) file,
\texttt{peace\_pre\_match.dta}, into \texttt{R}. However, for our
purposes, we recommend loading our pre-created .rds file
(\texttt{peace\_pre\_match.rds}), in which Stata's monthly numeric dates
have been converted to \texttt{R}'s year-month format and the geographic
region indicators recoded into a single factor variable
(\texttt{region}). The command below loads this pre-created dataset
(\texttt{peace\_pre\_match.rds}) into the \texttt{R} environment as an
object named \texttt{data}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define base URL for the Matching Guide GitHub repo}
\NormalTok{base\_url }\OtherTok{\textless{}{-}} \StringTok{"https://raw.githubusercontent.com/tl2624/matching{-}guide/main"}

\CommentTok{\# Load the cleaned dataset}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}
  \FunctionTok{url}\NormalTok{(}
    \FunctionTok{paste0}\NormalTok{(}
\NormalTok{      base\_url, }\StringTok{"/data/peace\_pre\_match.rds"}
\NormalTok{    )}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

\subsection{First Stage: Making a Matched Dataset (toward Justifying
As-If
Randomization)}\label{first-stage-making-a-matched-dataset-toward-justifying-as-if-randomization}

In an observational setting, treatment is not assigned by the flip of a
coin but depends on individuals' covariates. The goal of matching is to
compare treated and control units that have the same chances of
treatment based on those covariates --- i.e., the same \emph{propensity
scores}. If we could observe propensity scores, it would be
straightforward to compare treated and control units by matching them
directly on their propensity scores. Because propensity scores are not
directly observed, we instead aim to create a collection of matched sets
that is \emph{balanced} --- meaning that treated and control
observations are similar in their covariates.

Before turning to questions of covariate similarity and matching, it is
important to note that substantive transformations of covariates play a
central role, as they determine the inputs on which subsequent notions
of similarity between units are based. These transformations reflect
substantive judgments and are often among the most important decisions
in practice. In this manuscript, however, we do not address these
substantive choices. Instead, we take the transformations used by
\citet{gilligansergenti2008} as given. For example, they measure ethnic
fractionalization (\texttt{ethfrac}) on a 0-100 scale (rather than a
0--1 scale) and apply logarithmic transformations to covariates such as
the number of deaths (\texttt{lwdeaths}) and the duration of the
previous war (\texttt{lwdurat}), among others. Our focus is on design
and analysis decisions conditional on these substantively chosen scales.

\subsubsection{How Do I Measure Similarity on My Chosen
Covariates?}\label{how-do-i-measure-similarity-on-my-chosen-covariates}

In the simplest terms, matching is about ensuring apples-to-apples,
rather than apples-to-oranges, comparisons between treated and control
observations \citep{rubinwaterman2006}. To create matched sets in which
treated and control groups are similar in their covariates, we first
need a distance measure that quantifies how close any two observations
are. With such a measure in hand, we can then construct sets of treated
and control observations that are close on this measure --- i.e.,
apples-to-apples in their pre-treatment characteristics.

We record the distances between treated and control units in a distance
matrix: The rows correspond to treated units and the columns to control
units. Each cell of the matrix records the distance between a specific
treated unit and a specific control unit, as defined by a distance
measure. This distance measure takes the baseline covariates of the two
units and maps them to a single nonnegative number, with smaller values
indicating greater similarity.

In our setting, we are interested in similarity across \(9\) covariates,
named in the object \texttt{covs}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define character vector of the 9 covariate names in the dataset}
\NormalTok{covs }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"lwdeaths"}\NormalTok{, }\StringTok{"lwdurat"}\NormalTok{, }\StringTok{"ethfrac"}\NormalTok{, }\StringTok{"pop"}\NormalTok{, }\StringTok{"lmtnest"}\NormalTok{, }\StringTok{"milper"}\NormalTok{,}
          \StringTok{"bwgdp"}\NormalTok{, }\StringTok{"bwplty2"}\NormalTok{, }\StringTok{"region"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

The first four --- \texttt{lwdeaths}, \texttt{lwdurat},
\texttt{ethfrac}, and \texttt{pop} --- were introduced earlier. The
others include a logged measure of the proportion of a country's land
area that is mountainous (\texttt{lmtnest}), the logged total number of
military personnel in a country (\texttt{milper}), logged GDP per capita
before the last civil war (\texttt{bwgdp}), the Polity score (a \(-10\)
to \(10\) scale, from autocratic to democratic institutions) before the
last civil war (\texttt{bwplty2}), and a region factor (\texttt{region})
with categories for Eastern Europe, Latin America, Asia, Sub-Saharan
Africa, and North Africa/Middle East.

All of these covariates are measured before treatment and presumably
determine the chance of a UN intervention during a country's peace
period. Our interest in them stems primarily from their role in
determining those intervention probabilities. Yet many of these
covariates may also be prognostic; that is, they help predict the
outcome of interest in \citet{gilligansergenti2008}, the log duration of
the peace period (\texttt{ldur}) that countries would potentially
experience with or without a UN intervention. This prognostic value of
covariates can provide an additional reason to match on them
\citep{hansen2008a, salesetal2018}.

There are many ways to measure the distance between a treated and a
control unit. For example, we might compare units using the Euclidean
distance --- i.e., the square root of the sum of squared differences ---
across all baseline covariates. To do so, we first convert the factor
variable \texttt{region}, which stores categorical labels, into a set of
dummy (\(0\) or \(1\)) variables for each region. This conversion
ensures that distances between treated and control units can be
computed, since distance measures require numeric variables rather than
categorical labels.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install "dplyr" package (only run if not already installed)}
\CommentTok{\# install.packages("dplyr")}

\CommentTok{\# Load package for data manipulation (mutate, group\_by, summarize, etc.)}
\FunctionTok{library}\NormalTok{(dplyr)}

\CommentTok{\# Convert categorical variable "region" into 0/1 dummy indicators}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{|\textgreater{}} \CommentTok{\# Pipe (|\textgreater{}) to pass left{-}hand result into next function call}
  \FunctionTok{mutate}\NormalTok{(}
    \CommentTok{\# Use mutate() to create new variables by transforming existing columns}
    \CommentTok{\# ifelse() returns one value if condition is TRUE and another if FALSE}
    \AttributeTok{eeurop   =} \FunctionTok{ifelse}\NormalTok{(}\AttributeTok{test =}\NormalTok{ region }\SpecialCharTok{==} \StringTok{"eeurop"}\NormalTok{,   }\AttributeTok{yes =} \DecValTok{1}\NormalTok{, }\AttributeTok{no =} \DecValTok{0}\NormalTok{),}
    \AttributeTok{lamerica =} \FunctionTok{ifelse}\NormalTok{(}\AttributeTok{test =}\NormalTok{ region }\SpecialCharTok{==} \StringTok{"lamerica"}\NormalTok{, }\AttributeTok{yes =} \DecValTok{1}\NormalTok{, }\AttributeTok{no =} \DecValTok{0}\NormalTok{),}
    \AttributeTok{asia     =} \FunctionTok{ifelse}\NormalTok{(}\AttributeTok{test =}\NormalTok{ region }\SpecialCharTok{==} \StringTok{"asia"}\NormalTok{,     }\AttributeTok{yes =} \DecValTok{1}\NormalTok{, }\AttributeTok{no =} \DecValTok{0}\NormalTok{),}
    \AttributeTok{ssafrica =} \FunctionTok{ifelse}\NormalTok{(}\AttributeTok{test =}\NormalTok{ region }\SpecialCharTok{==} \StringTok{"ssafrica"}\NormalTok{, }\AttributeTok{yes =} \DecValTok{1}\NormalTok{, }\AttributeTok{no =} \DecValTok{0}\NormalTok{),}
    \AttributeTok{nafrme   =} \FunctionTok{ifelse}\NormalTok{(}\AttributeTok{test =}\NormalTok{ region }\SpecialCharTok{==} \StringTok{"nafrme"}\NormalTok{,   }\AttributeTok{yes =} \DecValTok{1}\NormalTok{, }\AttributeTok{no =} \DecValTok{0}\NormalTok{)}
\NormalTok{  )}

\CommentTok{\# Covariate names with "region" replaced by dummy indicators}
\NormalTok{expanded\_covs }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \CommentTok{\# setdiff() returns elements in \textquotesingle{}x\textquotesingle{} that are not in \textquotesingle{}y\textquotesingle{}}
  \FunctionTok{setdiff}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ covs,}
    \AttributeTok{y =} \StringTok{"region"} \CommentTok{\# Drops "region" from the covariate list}
\NormalTok{  ),}
  \StringTok{"eeurop"}\NormalTok{, }\StringTok{"lamerica"}\NormalTok{, }\StringTok{"asia"}\NormalTok{, }\StringTok{"ssafrica"}\NormalTok{, }\StringTok{"nafrme"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

As an example, we calculate the Euclidean distance between post-conflict
Liberia, where the UN did intervene, and post-conflict Guinea-Bissau,
where the UN did not.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract covariates for Liberia and Guinea{-}Bissau (cname = country name)}
\NormalTok{liberia }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{cname }\SpecialCharTok{==} \StringTok{"Liberia"}\NormalTok{, expanded\_covs]}

\NormalTok{guinea\_bissau }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{cname }\SpecialCharTok{==} \StringTok{"Guinea{-}Bissau"}\NormalTok{, expanded\_covs]}

\CommentTok{\# Compute Euclidean distance between the two countries on these covariates}
\FunctionTok{sqrt}\NormalTok{(}
  \FunctionTok{sum}\NormalTok{(}
\NormalTok{    (liberia }\SpecialCharTok{{-}}\NormalTok{ guinea\_bissau)}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{    )}
\NormalTok{  )  }\CommentTok{\# Display the Euclidean distance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 57.44263
\end{verbatim}

\doublespacing

We can obtain the full matrix of pairwise distance values using
\texttt{match\_on()} from the \texttt{optmatch} package. We do not need
to manually recode factor variables into dummy indicators because
\texttt{match\_on()} handles this conversion automatically.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a formula: UN (treatment indicator) \textasciitilde{} covariates}
\CommentTok{\# Note: we keep "region" in covs as a factor}
\NormalTok{cov\_fmla }\OtherTok{\textless{}{-}} \FunctionTok{reformulate}\NormalTok{(}
  \AttributeTok{termlabels =}\NormalTok{ covs,}
  \AttributeTok{response =} \StringTok{"UN"}
\NormalTok{)}

\CommentTok{\# Install optmatch if not already installed}
\CommentTok{\# install.packages("optmatch")}

\CommentTok{\# Load optmatch, which provides the match\_on() function}
\FunctionTok{library}\NormalTok{(optmatch)}

\CommentTok{\# Euclidean distance matrix: treated (UN = 1) vs control (UN = 0)}
\NormalTok{dist\_mat\_euc }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ cov\_fmla,                 }\CommentTok{\# Formula for covariates}
  \AttributeTok{data =}\NormalTok{ data,                  }\CommentTok{\# Dataset used}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{, }\CommentTok{\# No rescaling of covariates}
  \AttributeTok{method =} \StringTok{"euclidean"}          \CommentTok{\# Use Euclidean distance}
\NormalTok{)}

\CommentTok{\# Add country names (cname) as row/column labels for clarity}
\FunctionTok{dimnames}\NormalTok{(dist\_mat\_euc) }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{cname[data}\SpecialCharTok{$}\NormalTok{UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{], data}\SpecialCharTok{$}\NormalTok{cname[data}\SpecialCharTok{$}\NormalTok{UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{]}
\NormalTok{)}

\CommentTok{\# Display submatrix of distances:}
\FunctionTok{round}\NormalTok{(        }\CommentTok{\# Round distances for display}
  \CommentTok{\# treated units in rows 11{-}15 vs. control units in columns 27{-}30}
  \AttributeTok{x =}\NormalTok{ dist\_mat\_euc[}\DecValTok{11}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{27}\SpecialCharTok{:}\DecValTok{30}\NormalTok{],}
  \AttributeTok{digits =} \DecValTok{2}  \CommentTok{\# Number of decimal places to round}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
              Niger Guinea   Togo Central African Republic
Sierra Leone  94.21 101.18 116.32                   116.94
Zaire         26.68  29.87  45.63                    46.57
Rwanda        66.75  71.57  77.04                    76.03
Mozambique   133.47 140.60 155.40                   155.80
Namibia      246.44 253.23 268.35                   268.08
\end{verbatim}

\doublespacing

In this subset of the full distance matrix, the first entry is the
Euclidean distance of Sierra Leone (treated) from Niger (control). The
last listed entry is the distance between Namibia (treated) and the
Central African Republic (control).

One concern with Euclidean distance is that it depends on the scale of
the covariates. For example, the difference between a country in
Sub-Saharan Africa (\texttt{ssafrica} = 1) and a country in Latin
America (\texttt{ssafrica} = 0) would contribute the same to the
Euclidean distance as the difference between two countries with GDP per
capita values of \$3000 and \$3001. Intuitively, we would not want such
a tiny difference in economic size to be treated as equally important as
belonging to different regions of the world. More generally, we want
differences across variables to be placed on a comparable scale, so that
a meaningful difference in one variable counts about the same as a
difference of similar importance in another.

Another concern with Euclidean distance is that it ignores correlations
among covariates. For example, countries with larger populations
(\texttt{pop}) usually have more military personnel (\texttt{milper}),
if only because a larger population provides a greater pool of potential
recruits. Therefore, differences in both covariates (\texttt{pop} and
\texttt{milper}) may largely reflect the same underlying factor ---
population size (\texttt{pop}). Yet Euclidean distance adds these
differences separately, as if they were unrelated, which can exaggerate
the overall distance between two observations.

The Mahalanobis distance \citep{mahalanobis1936} addresses both of these
concerns. First, it standardizes covariates so that differences are
placed on a comparable scale. Second, the Mahalanobis distance adjusts
for correlations among covariates, ensuring that highly related
variables are not effectively counted twice. We can construct a distance
matrix based on Mahalanobis rather than Euclidean distances as follows.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mahalanobis distance matrix: treated (UN = 1) vs control (UN = 0)}
\NormalTok{dist\_mat\_mah }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ cov\_fmla,}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"mahalanobis"} \CommentTok{\# Use Mahalanobis distance}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

The standardization in the Mahalanobis distance is distinct from
researchers' substantive choices about how to transform covariates.
Substantive transformations --- such as logging certain covariates ---
reflect subject-matter considerations and precede the matching
procedure. The standardization in the Mahalanobis distance is a
statistical device that operates on the pre-specified covariates to
compute distances comparably across covariates. The purpose of this
device is to facilitate matches that are similar on the original
covariate scales.

\paragraph{Similarity on the Estimated Propensity
Score}\label{similarity-on-the-estimated-propensity-score}

So far, we have focused on ways to measure distance between treated and
control units across many covariates in order to identify which units
are most similar and group them together to achieve covariate balance.
However, when there are many covariates, it becomes difficult to find
treated and control units that are similar on all covariates. This
challenge is often referred to as the ``curse of dimensionality.''

A common way to address this problem is to reduce the information from
many covariates into a lower-dimensional form. The \emph{estimated
propensity score} does this by collapsing information from all
covariates into a single number. This number represents a transformation
of an estimated linear index of covariates that accounts for how
strongly each covariate predicts treatment.

Consider, for example, a logistic model for the estimated propensity
score of an individual unit \(i\). We write this model as
\begin{align} \label{eq: linear index}
\hat{\lambda}(\bm{x}_i) & = \dfrac{1}{1 + \exp(-\bm{\hat{\beta}}^{\top}\bm{x}_i)},
\end{align} where \(\bm{x}_i\) is the covariate vector,
\(\bm{\hat{\beta}}\) is the vector of estimated coefficients, and the
superscript \(^{\top}\) denotes the transpose, turning the row vector
\(\bm{\hat{\beta}}\) into a column vector. The quantity
\(\bm{\hat{\beta}}^{\top}\bm{x}_i\) is the estimated linear index, and
the inverse logistic function, \(1 / (1 + \exp(-x))\), maps any
real-valued input, \(x\), onto the interval \((0, \, 1)\). The estimated
linear covariate index for unit \(i\),
\(\bm{\hat{\beta}}^{\top}\bm{x}_i\), is simply the logit, i.e., log
odds, transformation of \(\hat{\lambda}(\bm{x}_i)\) in
\eqref{eq: linear index}.

This quantity, \(\hat{\lambda}(\bm{x}_i)\), is a simple transformation
of a linear index of covariates that best ``separates'' treated from
control units. The estimated coefficients (\(\bm{\hat{\beta}}\))
``separate'' treated from control units on the linear index because the
coefficients are chosen to maximize a likelihood that rewards large
differences between the groups. When treated and control units have
little or no covariate overlap, the estimated linear indices can diverge
substantially, very positive for treated units and very negative for
controls. With greater overlap, the estimated linear indices for treated
and control units are similar, clustering near zero.

This estimation process reflects how predictive each covariate is of
treatment. When treated and control observations lack overlap on a
covariate, that covariate is highly predictive of treatment and
therefore receives an estimated coefficient with a large magnitude. When
there is substantial overlap on a covariate, it is less predictive of
treatment, and the magnitude of its coefficient is small. Consequently,
when we assess similarity on the estimated linear index of covariates in
\eqref{eq: linear index}, the estimated coefficients assign greater
importance to covariates that strongly predict treatment and less
importance to those that do not.

To see this logic in action, we first estimate a logistic propensity
score model using all covariates except \texttt{region}, which we
exclude because some regions perfectly --- or nearly perfectly ---
predict treatment assignment, leading to (near-)complete separation
\citep{albertanderson1984}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Formula for UN \textasciitilde{} covariates (excluding "region")}
\NormalTok{psm\_cov\_fmla }\OtherTok{\textless{}{-}} \FunctionTok{reformulate}\NormalTok{(}
  \AttributeTok{termlabels =} \FunctionTok{setdiff}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ covs,}
    \AttributeTok{y =} \StringTok{"region"}
\NormalTok{  ),}
  \AttributeTok{response =} \StringTok{"UN"}
\NormalTok{)}

\CommentTok{\# Fit logistic regression for propensity score model}
\NormalTok{psm }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}
  \AttributeTok{formula =}\NormalTok{ psm\_cov\_fmla,            }\CommentTok{\# Treatment \textasciitilde{} covariates}
  \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{), }\CommentTok{\# Logistic regression (logit link)}
  \AttributeTok{data =}\NormalTok{ data}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Using this fitted propensity score model, we can extract each unit's
estimated linear covariate index, \(\bm{\hat{\beta}}^{\top} \bm{x}_i\),
as follows.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract logit propensity scores (linear predictors from fitted model)}
\NormalTok{lin\_cov\_inds }\OtherTok{\textless{}{-}}\NormalTok{ psm}\SpecialCharTok{$}\NormalTok{linear.predictors  }\CommentTok{\# = model.matrix(psm) \%*\% coef(psm)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Below we can see that the estimated linear covariate indices from the
model \texttt{psm} correspond exactly to the logits (i.e., the log-odds
transformations) of the model's predicted probabilities of treatment,
which range between \(0\) and \(1\).

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract estimated propensity scores (predicted probabilities of UN = 1)}
\NormalTok{p\_scores }\OtherTok{\textless{}{-}}\NormalTok{ psm}\SpecialCharTok{$}\NormalTok{fitted.values}

\CommentTok{\# Check that lin\_cov\_inds equals log odds (propensity scores on logit scale)}
\FunctionTok{all.equal}\NormalTok{(}
\NormalTok{  lin\_cov\_inds, }\FunctionTok{log}\NormalTok{(p\_scores }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ p\_scores))}
\NormalTok{)}

\CommentTok{\# Also check that p\_scores equals logistic(lin\_cov\_inds)}
\FunctionTok{all.equal}\NormalTok{(}
\NormalTok{  p\_scores, }\DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{lin\_cov\_inds))}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

To see how two observations that differ on many covariates can still
have similar estimated propensity scores, consider post-conflict Namibia
(treated) and Burundi (control). The two are similar on some covariates,
such as logged military personnel (\texttt{milper}), but --- consistent
with the ``curse of dimensionality'' --- very different on others, such
as duration of the last war (\texttt{lwdurat}) and ethnic
fractionalization (\texttt{ethfrac}). Yet the estimated linear indices
for Namibia and Burundi differ by only a minuscule amount. This small
difference occurs because the covariates on which Namibia and Burundi
differ greatly have small estimated coefficients in the propensity score
model (e.g., approximately -0.01 for \texttt{lwdurat} and approximately
0 for \texttt{ethfrac}), while those on which the two observations are
similar, such as \texttt{milper}, have large estimated coefficients
(approximately -0.92).

To illustrate these broader patterns, the boxplot below compares the
distributions of the estimated linear covariate index for treated and
control groups.

\singlespacing
\begin{figure}[H]

{\centering \includegraphics{Building_Design-Based_Matching_Pipeline_files/figure-latex/unnamed-chunk-11-1} 

}

\caption{The empirical distributions of the linear covariate index for treated and control groups.}\label{fig:unnamed-chunk-11}
\end{figure}
\doublespacing

As the figure above shows, there is some, but not a lot of, overlap
between treated and control groups. In accordance with our earlier
discussion of how the estimated linear covariate index ``separates''
treated from control units, many control observations have very negative
values (as low as -7.52), far from the treated units' range of -2.24 to
2.21. Nevertheless, a sufficient number of treated and control
observations have estimated linear covariate indices that cluster around
\(0\), indicating covariate overlap for at least a subset of treated and
control observations.

\subsubsection{How Can I Apply Rules for Matches to Ensure
Comparability?}\label{how-can-i-apply-rules-for-matches-to-ensure-comparability}

The discussion above on measuring covariate distances between treated
and control observations helps identify which treated-control pairs are
similar. The goal of identifying these similar treated-control pairs is
to form matched sets that are closely aligned on their covariates,
thereby improving balance between treatment and control groups. In
practice, we do this by excluding potential matches that are ``too
dissimilar.'' There are two common ways to do this:

\begin{itemize}
\tightlist
\item
  \textbf{Exact matching}: Require that units be identical on some
  subset of important covariates, typically those that are categorical
  or coarse enough for units to take the same values.
\item
  \textbf{Calipers}: Impose a threshold for the maximum allowable
  distance so that no matched set may include a treated and a control
  unit that are farther apart than this caliper.
\end{itemize}

As a simple example to build intuition, we will impose the following
constraints:

\begin{itemize}
\tightlist
\item
  Observations can belong to the same matched stratum only if they are
  in the same geographic region.
\item
  Treated and control observations more than two points apart on the
  Polity score cannot be in the same matched set.
\end{itemize}

Below we impose the first constraint, requiring an exact match on
region. Doing so produces separate distance matrices containing the
Euclidean distances on the covariate used to define the exact match
(\texttt{region}), where all entries are \(0\), indicating that treated
and control units belong to the same region.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create distance structure: 0 if units are in same region, Inf otherwise}
\NormalTok{em\_region }\OtherTok{\textless{}{-}} \FunctionTok{exactMatch}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ region,}
  \AttributeTok{data =}\NormalTok{ data}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Now we impose the second constraint: We construct a distance matrix
based on the Polity score, \texttt{bwplty2}, with a caliper of \(2\).
This matrix records the Euclidean difference in Polity scores when the
difference is \(2\) or less, and assigns a value of \(\infty\) (denoted
in \texttt{R} as \texttt{Inf}) when the difference exceeds \(2\). The
\(\infty\) entries are crucial because \texttt{optmatch} minimizes the
sum, across all matched sets, of the within-set sums of covariate
distances between each treated-control pair. Consequently, any
treated--control pair differing by more than 2 points on the Polity
score is assigned an overall distance of \(\infty\), which prevents them
from being matched.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Euclidean distance on Polity score (bwplty2) with caliper = 2}
\CommentTok{\# Pairs differing by \textgreater{} 2 are set to Inf}
\NormalTok{euc\_dist\_polity\_cal\_2 }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ bwplty2,}
  \AttributeTok{caliper =} \DecValTok{2}\NormalTok{,  }\CommentTok{\# Set caliper}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"euclidean"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Note that we used Euclidean distance here because, after exactly
matching on geographic region, matching proceeds on only \(1\) covariate
(Polity score), so we do not have to worry about covariates' relative
scales.

Finally, we combine the two constraints into distance matrices defined
within each region by
`\texttt{adding\textquotesingle{}\textquotesingle{}\ the\ objects}em\_region\texttt{and}euc\_dist\_polity\_cal\_2`,
as shown below.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Overall distance matrix by element{-}wise addition of two distance matrices}
\NormalTok{overall\_dist\_mat }\OtherTok{\textless{}{-}}\NormalTok{ em\_region }\SpecialCharTok{+}\NormalTok{ euc\_dist\_polity\_cal\_2}
\end{Highlighting}
\end{Shaded}

\doublespacing

\subsubsection{How Can I Apply Rules for Matches to Improve Effective
Sample
Size?}\label{how-can-i-apply-rules-for-matches-to-improve-effective-sample-size}

Beyond comparability in covariates, we also care about the matched
study's size. The effective sample size depends not simply on the total
number of units included in our matches. Effective sample size also
depends on how those units are arranged across the matched sets.

The \texttt{optmatch} package will always produce matches with a
particular arrangement of units across sets. In particular, all sets
contain either \(1\) treated unit or \(1\) control unit --- an overall
structure that minimizes imbalance while excluding as few units as
possible \citep{rosenbaum1991, gurosenbaum1993, hansen2004}. In
practice, optimal full matching can yield lopsided sets, with either
\(1\) treated matched to many controls or \(1\) control matched to many
treated units, which has implications for the effective sample size.

In the \texttt{optmatch} package, the effective sample size is defined
as the sum, across matched sets, of the harmonic mean of the numbers of
treated and control units within each set. The formal definition is
given by \begin{align} \label{eq: harmonic mean}
\textbf{Effective Sample Size:} \quad \sum \limits_{s = 1}^S \left[\left(m_s^{-1} + (n_s - m_s)^{-1}\right)/2\right]^{-1},
\end{align} where the index \(s\) runs over the
\(\left\{1, \dots , S\right\}\) matched sets, with \(m_{s}\) denoting
the number of treated units in set \(s\) and \(n_s - m_s\) the number of
control units. With \(n_s\) denoting the number of units in set \(s\),
the total number of individuals included in the matched study is
\(n = \sum_{s = 1}^S n_s\).

From the formula in \eqref{eq: harmonic mean}, we can see how the
effective sample size depends on the arrangement of units across sets.
For example, in a study with \(4\) total units, the effective sample
size would be \(2\) if the units were arranged into \(2\) matched pairs.
By contrast, in a study of the same total size but arranged as a single
set with \(1\) treated unit and \(3\) controls, the effective sample
size would be \(1.5\). The effective sample size is larger in the former
arrangement because it provides two distinct treated-versus-control
comparisons, whereas the latter provides only one.

This definition of effective sample size anticipates subsequent outcome
analysis under as-if randomization, as effective sample size bears
directly on the precision of estimators and the power of hypothesis
tests. Assuming constant, additive treatment effects within a set, the
variance of the Difference-in-Means --- the average outcome among
treated units minus the average outcome among control units --- in that
set is minimized when the harmonic mean is largest
\citep{hansenbowers2008, hansen2011}. The harmonic mean reaches its
maximum when the numbers of treated and control units are equal. Thus,
all else equal, matched pairs and other balanced sets provide more
information about causal effects than lopsided sets with unequal
treated-to-control ratios.

One straightforward way to increase effective sample size is to relax
restrictions on which units can be matched. Relaxing calipers can admit
additional units into the matched design by allowing matches for units
that would otherwise be discarded. For instance, we might widen the
caliper on Polity score from \(2\) to \(3\) and then rebuild the
distance matrix.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Apply a caliper of width 3 to the polity Euclidean distance matrix}
\NormalTok{euc\_dist\_polity\_cal\_3 }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ bwplty2,}
  \AttributeTok{caliper =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"euclidean"}
\NormalTok{)}

\CommentTok{\# Combine regional exact match distance with polity distance}
\NormalTok{em\_region }\SpecialCharTok{+}\NormalTok{ euc\_dist\_polity\_cal\_3}
\end{Highlighting}
\end{Shaded}

\doublespacing

Doing so increases the effective sample size, but such gains need not be
substantial. When newly admitted units are absorbed into existing
matched sets --- each of which contains only one treated or one control
unit --- rather than generating additional treated--versus-control
comparisons, the resulting contribution to effective sample size is
limited. More generally, as the formula in \eqref{eq: harmonic mean}
makes clear, the effective sample size depends on how units are
distributed across sets: When units, including newly admitted ones, are
concentrated in only a few sets, the resulting gain in effective sample
size is modest.

Instead of relying solely on caliper width, researchers can also shape
the effective sample size by controlling the structure of matched sets
via the \texttt{min.controls} and \texttt{max.controls} arguments in
\texttt{optmatch}'s \texttt{fullmatch()} function. These arguments
specify lower and upper bounds, respectively, on the ratio of control to
treated units within each matched set. By default,
\texttt{min.controls\ =\ 0} and \texttt{max.controls\ =\ Inf}, which
impose no restrictions on matched set composition. Changing these
defaults allows researchers to control how balanced or lopsided matched
sets may be, thereby shaping the effective sample size.

To illustrate, suppose we want to restrict matches using the
\texttt{overall\_dist\_mat} introduced earlier. We know that
\texttt{optmatch} will divide the data into matched sets containing one
treated unit and any positive number of controls, or one control unit
and any positive number of treated units. However, we can impose
additional constraints on this full matching, such as requiring a
minimum control-to-treated ratio of \(1{:}2\) --- that is, at least one
control for every two treated units (\texttt{min.controls\ =\ 0.5}) ---
and no more than two controls per treated unit
(\texttt{max.controls\ =\ 2}). Under these restrictions, allowable
matched sets could include \(2\) treated units with \(1\) control, \(1\)
treated unit with \(1\) control (a matched pair), or \(1\) treated unit
with \(2\) controls.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Full matching using overall distance matrix}
\FunctionTok{fullmatch}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ overall\_dist\_mat,}
  \AttributeTok{min.controls =} \FloatTok{0.5}\NormalTok{,   }\CommentTok{\# At least 0.5 controls per treated unit}
                        \CommentTok{\# (i.e., no more than 2 treated per control)}
  \AttributeTok{max.controls =} \DecValTok{2}\NormalTok{,     }\CommentTok{\# At most 2 controls per treated unit}
  \AttributeTok{omit.fraction =} \ConstantTok{NULL}\NormalTok{, }\CommentTok{\# Governs fraction of units discarded}
  \AttributeTok{mean.controls =} \ConstantTok{NULL}\NormalTok{, }\CommentTok{\# Governs average controls per treated unit}
  \CommentTok{\# Only one of omit.fraction or mean.controls can be non{-}NULL}
  \AttributeTok{data =}\NormalTok{ data}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Note, in addition, that the \texttt{fullmatch()} arguments of
\texttt{omit.fraction} and \texttt{mean.controls} provide explicit
levers for controlling how many treated and control units are discarded,
though at most one of \texttt{omit.fraction} or \texttt{mean.controls}
may be specified.

Imposing ratio constraints can have mixed consequences. In some cases,
balance may worsen if a control is forced to match with a less similar
treated unit --- though still within the specified calipers --- in order
to satisfy the minimum and maximum ratio rules. In other cases, such
constraints may improve effective sample size by redistributing how
units are grouped without hurting balance. However, if the ratio
constraints are too stringent, they can reduce effective sample size by
forcing too many units to be discarded.

In applied settings, final choices of calipers and ratio constraints
typically follow iterative checks of both covariate balance and
effective sample size. Practitioners often compare several
specifications and select among those that satisfy diagnostics for both
goals. \citet{hansensales2015} outline how this process can be carried
out in a structured way, drawing on the stepwise intersection--union
principle (SIUP) of hypothesis testing.

\subsubsection{How Do I Actually Form the
Matches?}\label{how-do-i-actually-form-the-matches}

The simple matching example above --- based on an exact match on
geographic region and a caliper on Euclidean distance for a single
covariate (Polity score) --- serves to illustrate the basic ideas. When
matching on many covariates, however, we will often prefer some
combination of Mahalanobis distance and propensity score matching,
sometimes adding calipers on specific covariates. In what follows, we
use \emph{rank-based} Mahalanobis distance, which has the advantage of
being less sensitive to outliers and differences in scales across
covariates \citep{rosenbaum2010}. We further constrain the matching by
imposing a caliper on the estimated propensity score, requiring treated
and control observations to come from the same geographic region, and
applying additional calipers directly to two covariates: ethnic
fractionalization (\texttt{ethfrac}) and logged GDP per capita
(\texttt{bwgdp}).

We impose a caliper equal to \(0.5\) standard deviations of the logit of
the estimated propensity score (the estimated linear covariate index
defined above). This choice is larger than one rule of thumb emanating
from \citet{cochranrubin1973}, which recommends a caliper less than or
equal to \(0.20\) standard deviations. Given that the standard deviation
of the logit index is approximately 1.96, our choice of \(0.5\) permits
treated and control units to differ by up to roughly 0.98 on the logit
scale, compared to about 0.39 under the \(0.20\) guideline.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Add logistic regression linear predictors to dataset}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{logit\_p\_score }\OtherTok{\textless{}{-}}\NormalTok{ lin\_cov\_inds}

\CommentTok{\# Population standard deviation of logit\_p\_score (divides by n, not n {-} 1)}
\NormalTok{pop\_sd\_logit }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}
  \FunctionTok{mean}\NormalTok{(}
\NormalTok{    (data}\SpecialCharTok{$}\NormalTok{logit\_p\_score }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{logit\_p\_score))}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# Distance matrix for logit of estimated propensity scores}
\NormalTok{ps\_mat }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ logit\_p\_score,}
  \AttributeTok{caliper =} \FloatTok{0.5} \SpecialCharTok{*}\NormalTok{ pop\_sd\_logit,}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"euclidean"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Below we construct the distance matrix for rank-based Mahalanobis
distance.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Rank{-}based Mahalanobis distance on covariates}
\CommentTok{\# Covs defined earlier as covariate names; here, drop "region"}
\NormalTok{rank\_mah\_mat }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x      =} \FunctionTok{reformulate}\NormalTok{(}
    \AttributeTok{termlabels =} \FunctionTok{setdiff}\NormalTok{(}
      \AttributeTok{x =}\NormalTok{ covs,}
      \AttributeTok{y =} \StringTok{"region"}\NormalTok{),}
    \AttributeTok{response   =} \StringTok{"UN"}\NormalTok{),}
  \AttributeTok{data   =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"rank\_mahalanobis"} \CommentTok{\# Use rank{-}based Mahalanobis distance}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Finally, we construct the Euclidean distance matrix for ethnic
fractionalization (\texttt{ethfrac}) and logged GDP per capita
(\texttt{bwgdp}) using calipers of \(35\) and \(2\), respectively. The
exact-match constraint on region has already been defined through the
object \texttt{em\_region} above.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute Euclidean distance matrix for ethnic fractionalization}
\NormalTok{eth\_mat }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ethfrac,}
  \AttributeTok{caliper =} \DecValTok{35}\NormalTok{,}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"euclidean"}
\NormalTok{)}

\CommentTok{\# Compute Euclidean distance matrix for logged GDP per capita}
\NormalTok{bwgdp\_mat }\OtherTok{\textless{}{-}} \FunctionTok{match\_on}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}}\NormalTok{ bwgdp,}
  \AttributeTok{caliper =} \DecValTok{2}\NormalTok{,}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{standardization.scale =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{method =} \StringTok{"euclidean"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

We then combine the \texttt{ps\_mat}, \texttt{rank\_mah\_mat},
\texttt{eth\_mat}, \texttt{bwgdp\_mat}, and \texttt{em\_region} objects
to form the overall distance structure. We then pass the combined object
to \texttt{optmatch}'s \texttt{fullmatch()} function, imposing a
constraint that no more than \(4\) control units may be matched to any
treated unit. If instead we wanted to perform pair matching, the
\texttt{optmatch} package allows users to directly specify a
matched-pair structure via the \texttt{pairmatch()} function.
Equivalently, we could implement pair matching by setting
\texttt{min.controls\ =\ 1} and \texttt{max.controls\ =\ 1} in the
\texttt{fullmatch()} call. The code chunk below proceeds with full
matching under the constraint that no more than \(4\) controls may be
matched to any treated unit.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Full matching: }
\CommentTok{\# PS + rank Mahalanobis + Euclidean (ethfrac, bwgdp) + region exact}
\NormalTok{fm }\OtherTok{\textless{}{-}} \FunctionTok{fullmatch}\NormalTok{(}
\CommentTok{\# x specifies the distance structure:}
\CommentTok{\# match\_on() formula, distance matrix, or sum of match\_on() distances}
  \AttributeTok{x            =}\NormalTok{ ps\_mat }\SpecialCharTok{+}\NormalTok{ rank\_mah\_mat }\SpecialCharTok{+}\NormalTok{ eth\_mat }\SpecialCharTok{+}\NormalTok{ bwgdp\_mat }\SpecialCharTok{+}\NormalTok{ em\_region,}
  \AttributeTok{data         =}\NormalTok{ data,}
  \AttributeTok{max.controls =} \DecValTok{4} \CommentTok{\# \textless{}= 4 controls per treated (min.controls = 0 by default)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

To calculate the effective sample size of the matched observations, we
use the following function from \texttt{optmatch}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Effective sample size of matched sets}
\FunctionTok{effectiveSampleSize}\NormalTok{(}
\NormalTok{  fm}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 15.26667
\end{verbatim}

\doublespacing

Referring back to \eqref{eq: harmonic mean}, this reported effective
sample size of approximately 15.27 equals the sum across sets of the
within-set harmonic mean of the number of treated and control subjects.
This effective sample size reflects the matched structure in which no
set contains more than \(4\) controls for any \(1\) treated observation.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Summarize matched sets and report effective sample size}
\FunctionTok{summary}\NormalTok{(}
\NormalTok{  fm}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Structure of matched sets:
1:0 2:1 1:1 1:2 1:3 1:4 0:1 
  6   1   4   4   2   1  45 
Effective Sample Size:  15.3 
(equivalent number of matched pairs).
\end{verbatim}

\doublespacing

The notation in the \texttt{summary()} output of \texttt{optmatch}
indicates the ratio of treated to control observations within each
matched set. For example, \texttt{1:0} indicates \(1\) treated unit and
no controls (effectively an unmatched treated unit). Similarly,
\texttt{1:2} indicates \(1\) treated unit and \(2\) controls, and
\texttt{0:1} indicates no treated units and \(1\) control (effectively
an unmatched control). Below each label, the output shows how many
matched sets have that particular structure.

If we examine the object returned by the matching call (\texttt{fm}), we
see that \texttt{optmatch} labels each observation according to its
matched set, assigning \texttt{NA} to those not included. Because we
performed exact matching by region, \texttt{optmatch} labels each
matched set using the name of the exact-match stratum followed by a set
index within that stratum. For example, the label \texttt{lamerica.1}
denotes the first matched set within the Latin America stratum.

To see which units were matched together, we can add the \texttt{fm}
object to the dataframe and then tabulate. For example, to view the
\texttt{ssafrica.3} set, we run the following.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Add matched set ID to data for each unit}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{fm }\OtherTok{\textless{}{-}}\NormalTok{ fm}

\CommentTok{\# Look at one matched set ("ssafrica.3") for illustration}
\NormalTok{data }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    fm }\SpecialCharTok{==} \StringTok{"ssafrica.3"} \CommentTok{\# Keep only units in set "ssafrica.3"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Display selected variables}
  \FunctionTok{select}\NormalTok{(}
\NormalTok{    cname, UN, region, logit\_p\_score, ethfrac, bwgdp, bwplty2}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 4 x 7
  cname      UN region   logit_p_score ethfrac bwgdp bwplty2
  <chr>   <dbl> <fct>            <dbl>   <dbl> <dbl>   <dbl>
1 Burundi     0 ssafrica         0.508    3.55  5.35      -7
2 Rwanda      1 ssafrica         0.148   12.9   5.68      -7
3 Somalia     0 ssafrica         0.209    7.67  6.61      -7
4 Lesotho     0 ssafrica         0.558   22.2   6.28       0
\end{verbatim}

\doublespacing

We can see that the exact match on geographic region holds: All \(4\)
countries are located in Sub-Saharan Africa. The logit of the estimated
propensity score is similar across units, though not identical. The
treated country, Rwanda, is matched to three controls --- Burundi,
Somalia, and Lesotho --- and in each case the distance falls within
\(0.5\) standard deviations of the estimated logit propensity scores
(approximately 0.98), the caliper we specified. Likewise, Rwanda's
distances to each of the \(3\) control units fall within the calipers of
\(35\) for ethnic fractionalization (\texttt{ethfrac}) and \(2\) for
logged GDP per capita (\texttt{bwgdp}). By contrast, distances between
control countries can technically exceed these thresholds, since
\texttt{optmatch} enforces calipers only between treated and control
units, not among controls.

We can also see that some covariates used in the propensity score model
and the rank-based Mahalanobis distance --- such as Polity score
(\texttt{bwplty2}) --- still show modest imbalance within this matched
set. This imbalance is unsurprising. We applied a caliper on the logit
of the estimated propensity score and matched on the rank-based
Mahalanobis distance including \texttt{bwplty2}, but we did not apply a
caliper directly to \texttt{bwplty2}, though such a caliper could easily
be added if desired.

\subsubsection{How Do I Decide Whether to Move Ahead with My Matched
Design?}\label{how-do-i-decide-whether-to-move-ahead-with-my-matched-design}

Once we have constructed our matched sets, we want to evaluate the
overall quality of the matched design. Covariate balance is an important
aspect of this evaluation. To assess covariate balance, we compare the
balance in our matched observational study with the balance we would
expect to see in a completely randomized experiment within blocks
\citep{hansenbowers2008}.

Below we calculate adjusted covariate means for the treated and control
groups by averaging set-specific means across matched sets, with each
set weighted by its contribution to the effective sample size. We also
report standardized differences, defined as the treated-minus-control
difference in these adjusted means divided by the pooled standard
deviation of the covariate across treated and control units in the
overall data (including both matched and unmatched units).

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install "RItools" package (only run if not already installed)}
\CommentTok{\# install.packages("RItools")}

\CommentTok{\# Load RItools package for balance diagnostics (balanceTest)}
\FunctionTok{library}\NormalTok{(RItools)}
\CommentTok{\# Covariate balance test}
\NormalTok{cov\_bal }\OtherTok{\textless{}{-}} \FunctionTok{balanceTest}\NormalTok{(}
  \CommentTok{\# Formula: treatment \textasciitilde{} covariates}
  \CommentTok{\# update(): keep the original formula (. \textasciitilde{} .)}
  \CommentTok{\# and add stratification by matched set, + strata(fm)}
  \AttributeTok{fmla =} \FunctionTok{update}\NormalTok{(}
\NormalTok{    cov\_fmla, . }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{+} \FunctionTok{strata}\NormalTok{(fm)}
\NormalTok{  ),}
  \AttributeTok{data =}\NormalTok{ data,}
  \AttributeTok{p.adjust.method =} \StringTok{"none"} \CommentTok{\# Method of p{-}value adjustment (none here)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

\singlespacing
\begin{table}[!h]
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lcccccc}
\toprule
\multicolumn{1}{c}{\textbf{ }} & \multicolumn{3}{c}{\textbf{Before matching}} & \multicolumn{3}{c}{\textbf{After matching}} \\
\cmidrule(l{3pt}r{3pt}){2-4} \cmidrule(l{3pt}r{3pt}){5-7}
Covariate & Control mean & Treated mean & Std. diff & Control mean & Treated mean & Std. diff\\
\midrule
Log Cumulative Battle Deaths from Last War & 6.65 & 8.98 & 0.84* & 8.34 & 8.57 & 0.08\\
Duration of Last War & 50.28 & 80.53 & 0.39 & 60.51 & 73.23 & 0.16\\
Ethnic Fractionalization & 56.50 & 49.21 & -0.28 & 51.75 & 57.50 & 0.22\\
Log Population Size & 9.51 & 8.75 & -0.64* & 8.89 & 8.91 & 0.02\\
Log Mountainous & 2.22 & 2.80 & 0.43 & 2.69 & 2.82 & 0.09\\
Log Military Personnel & 3.87 & 3.25 & -0.42 & 3.63 & 3.54 & -0.06\\
Log GDP per Capita Before Last War & 6.56 & 6.59 & 0.03 & 6.73 & 6.55 & -0.17\\
Democracy (Polity Score) Before Last War & -0.84 & -2.58 & -0.32 & -2.19 & -2.54 & -0.07\\
Asia & 0.19 & 0.00 & -0.68* & 0.00 & 0.00 & 0.00\\
Eastern Europe & 0.15 & 0.37 & 0.51* & 0.46 & 0.46 & 0.00\\
Latin America & 0.12 & 0.21 & 0.25 & 0.08 & 0.08 & 0.00\\
North Africa \& Middle East & 0.12 & 0.11 & -0.04 & 0.08 & 0.08 & 0.00\\
Sub-Saharan Africa & 0.43 & 0.32 & -0.23 & 0.38 & 0.38 & 0.00\\
\bottomrule
\end{tabular}}
\captionof{table}{Adjusted covariate means for treated and control groups and standardized treated--control differences, before and after matching. Asterisks denote two-tailed $p$-values less than or equal to 0.05.}
\label{tab: balance}
\end{table}
\doublespacing

\FloatBarrier

In Table \ref{tab: balance} above, the adjusted means offer a direct
description of balance. The standardized differences place all
covariates on a common scale, enabling at-a-glance comparisons of
imbalance across covariates. Stars indicate covariates for which the
adjusted mean difference would be unusually extreme under a
block-randomized experiment that assigns treatment completely at random
within matched sets, holding fixed the observed number of treated units
in each set. The stars are based on a Normal approximation to the
randomization distribution of adjusted mean differences, and, because no
adjustments are made for multiple comparisons, these stars are
conservative. That is, for any given covariate, the corresponding
adjusted mean difference is, if anything, more likely than the nominal
rate to fall in the tails of its own randomization distribution under
complete random assignment within matched sets. Alternative adjustments
for testing multiple covariates are available, such as the Holm
procedure \citep{holm1979}, which is the default option in
\texttt{RItools}'s \texttt{balanceTest()} function.

One concern with balance tests is that high \(p\)-values may arise not
from improved covariate balance but from the reduction in effective
sample size that typically accompanies the matching process
\citep{austin2008, imaietal2008}. As \citet{hansen2008b} notes, however,
this possibility is less troubling than it first appears. The same
increase in standard errors that produces high \(p\)-values for
covariate balance tests will also carry over to subsequent causal
inferences, meaning that those high \(p\)-values remain informative:
They suggest that we are, if anything, less likely to overstate our
causal conclusions than if the \(p\)-values had been significant.

Regardless of whether the balance tests are statistically significant,
there are also established guidelines for what constitutes sufficient
balance. While precise thresholds depend on context and substantive
judgment about each covariate's importance, two rules of thumb appear in
\citet{austin2009} and \citet{stuart2010}. \citet{austin2009} suggests
that standardized differences of 0.1 or greater indicate inadequate
balance on a covariate, whereas \citet{stuart2010}, following
\citet{rubin2001}, proposes a more lenient threshold of 0.25. In our
case, all covariates meet this latter standard, and none show
statistically significant differences, indicating that observed
imbalances would not be unusual under a completely randomized experiment
within blocks (i.e., under as-if randomization).

In addition to assessing balance on each covariate individually,
\citet{hansenbowers2008} also propose an omnibus, chi-squared
(\(\chi^2\)) test that evaluates balance across all covariates and their
linear combinations simultaneously. We conduct this test below.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract overall chi{-}square balance test by matched set (fm)}
\NormalTok{cov\_bal}\SpecialCharTok{$}\NormalTok{overall[}\StringTok{"fm"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   chisquare df   p.value
fm  2.631007  8 0.9553417
\end{verbatim}

\doublespacing

This \(\chi^2\) balance test yields an observed test statistic of 2.63
and a corresponding \(p\)-value of 0.96. Our high \(p\)-value indicates
that the observed level of covariate balance is consistent with what we
would expect in a completely randomized experiment within blocks.

Despite the high \(p\)-value, there is no guarantee that balance is
sufficient for as-if randomization. Residual imbalance on observed
covariates and hidden imbalance on unobserved ones may undermine the
as-if randomization assumption. For now, we proceed under the as-if
randomization assumption, but we will later assess how sensitive our
inferences are to violations of it due to such imbalances.

\subsection{Second Stage: Causal Inference (under As-If
Randomization)}\label{second-stage-causal-inference-under-as-if-randomization}

In both the sharp and weak frameworks, the causal targets of inference
are defined through potential outcomes. Under what is known as SUTVA,
the stable unit treatment value assumption
\citep{rubin1980, rubin1986, cox1958}, each unit has two potential
outcomes: a value the outcome would take if that unit were assigned to
treatment and a value the outcome would take if that unit were assigned
to control. Let \(y_{si}(1)\) and \(y_{si}(0)\) denote these potential
outcomes, respectively, for unit \(i\) in set \(s\), where the index
\(i\) runs over the \(\{1, \ldots, n_s\}\) units in set \(s\). The
individual treatment effect is \(\tau_{si} = y_{si}(1) - y_{si}(0)\).
With \(n = \sum_{s = 1}^S n_s\) total units, let
\(\bm{\tau} = (\tau_{1,1}, \tau_{1,2}, \ldots, \tau_{S,n_s})^{\top}\)
collect all \(n\) unit-level effects, indexed first by matched set and
then by unit within set, and write the ATE as
\(\tau = (1/n) \sum_{s=1}^S \sum_{i=1}^{n_s} \tau_{si}\).

Both \(\bm{\tau}\) and \(\tau\) are defined only for the subset of units
retained after matching, which often differs from the original set of
units prior to matching \citep{rosenbaumrubin1985, rosenbaum2012}. This
difference is especially important when retention is driven by overlap
in the estimated propensity score, as the resulting study population can
be difficult to interpret substantively. In such settings, it is often
preferable to define the study population directly in terms of a small
number of substantively meaningful covariates, reflecting the argument
in \citet{rosenbaum2010} that it is ``usually better to go back to the
covariates themselves \ldots{} perhaps redefining the population under
study to be a subpopulation of the original population'' (p.~86), as
also emphasized by \citet{stuart2010}. Building on this insight,
subsequent approaches seek to define the matched study population
directly in terms of a small number of substantively meaningful
covariates \citep{fogartyetal2016, traskinsmall2011}.

The breadth of the study population retained after matching depends in
part on the relative abundance of treated and control units across
covariate space. When one treatment arm is sparsely represented in
regions dominated by the other, overlap may be limited to a narrow
region of covariate space and include relatively few units. All else
equal, a larger pool of units available for matching supports overlap
over a wider region of covariate space and a larger, more interpretable
study population over which the target of inference is defined.

These targets of inference, \(\bm{\tau}\) nor \(\tau\), defined among
the matched units, cannot be directly calculated. Even in a randomized
experiment, we cannot assign a country emerging from civil war to
receive a UN peacekeeping mission, observe how long the ensuing peace
lasts, and then rewind time to observe how long peace would have lasted
in the absence of a UN peacekeeping mission. In other words, for each
unit we observe only one of its two potential outcomes. Let \(y_{si}\)
denote this observed outcome, which equals the treated potential outcome
when unit \(i\) in set \(s\) receives the treatment and the control
potential outcome otherwise. Because the individual-level causal effect
can never be directly observed --- only one potential outcome is
realized for each unit --- we must rely on statistical inference to draw
conclusions about \(\bm{\tau}\) and \(\tau\).

We consider inference under the sharp and weak frameworks, targeting
\(\bm{\tau}\) and \(\tau\), respectively. Ongoing work shows how both
types of effects can be inferred simultaneously under as-if
randomization
\citep{chungromano2013, ding2017, wuding2021, cohenfogarty2022}, though
they cannot generally be unified in sensitivity analyses
\citep{fogarty2023}. When researchers must choose between the two, the
decision depends on both statistical properties and substantive goals.

\begin{itemize}
\item
  Statistically, the sharp framework specifies all missing potential
  outcomes, allowing exact randomization inference under minimal
  assumptions. The weak framework leaves some outcomes unspecified and
  instead relies on variance estimation and a Normal approximation,
  which can perform poorly in small samples or when outcomes are skewed
  with extreme outliers. In such cases --- or whenever one wants exact
  \(p\)-values under minimal assumptions --- permutation inference under
  the sharp framework may be preferable.
\item
  Substantively, researchers usually test a constant effect in the sharp
  framework. Such a hypothesis may be unrealistic or of limited
  scientific interest \citep{gelman2003, gelman2011}. The weak
  framework, by contrast, accommodates heterogeneous effects across
  units, making the ATE a more relevant target in many settings.
  Nevertheless, tests of a constant effect can provide a useful
  approximation to a more complex hypothesis with heterogeneous effects
  \citep[pp.~44--46]{rosenbaum2010}, and such tests remain valid for a
  range of bounded but heterogeneous effects \citep{caugheyetal2023}.
\end{itemize}

\paragraph{The Assignment Process as the Basis for
Inference}\label{the-assignment-process-as-the-basis-for-inference}

Regardless of the framework, inference is based on the treatment
assignment process. Let \(z_{si}\) denote an indicator for whether unit
\(i\) in matched set \(s\) is treated (\(z_{si} = 1\)) or not
(\(z_{si} = 0\)). We collect these indicators for all units in set \(s\)
into the vector \(\bm{z}_s = (z_{s1}, \ldots, z_{sn_s})^{\top}\).
Stacking these vectors across all sets gives the full assignment vector
\(\bm{z} = (z_{11}, \ldots, z_{Sn_S})^{\top}\), again indexed first by
matched set and then by unit within set. For inference, we condition on
the number of treated units within each set, \(m_s\), even if the actual
assignment mechanism were to consist of \(n_s\) independent assignments.
For further discussion of this form of ``conditional as-if analysis,''
see \citet{pashleyetal2021} and \citet[pp.~289--290, fn.
15]{rosenbaum2017}.

We denote by \(\Omega_s\) the set of all possible treatment assignments
in set \(s\), holding fixed the observed number of treated units in that
set. Formally, \(\Omega_s\) includes every possible way the \(n_s\)
units in set \(s\) could be assigned to treatment and control such that
exactly \(m_s\) units are treated. The number of possible assignments in
\(\Omega_s\) is denoted by \(\abs{\Omega_s}\), where the notation
\(\abs{\cdot}\) indicates the number of elements in a set. This quantity
equals
\(\abs{\Omega_s} = \binom{n_s}{m_s} = n_s! / [m_s! (n_s - m_s)!]\),
where ``!'' denotes the factorial operator (e.g.,
\(4! = 4 \times 3 \times 2 \times 1\)).

In the \texttt{ssafrica.3} set, for example, there are \(4\)
observations --- \(1\) treated and \(3\) control --- so
\(\abs{\Omega_s}\) for the \texttt{ssafrica.3} set is
\(\binom{4}{1} = 4\). The corresponding set of possible assignments with
this treated count is shown in the table below.

\singlespacing
\begin{table}[htbp]
\centering
\begin{tabular}{l|cccc}
\hline
 & Assignment 1 & Assignment 2 & Assignment 3 & Assignment 4
 \\
\hline
Burundi & 0 & 0 & 0 & 1 \\
Rwanda & 0 & 0 & 1 & 0 \\
Somalia & 0 & 1 & 0 & 0 \\
Lesotho & 1 & 0 & 0 & 0 \\
\hline
\end{tabular}
\caption{All possible treatment assignments within matched set \texttt{ssafrica.3}, holding fixed the observed number of treated units in that set.}
\label{tab: ssafrica.3 assignments}
\end{table}
\doublespacing

\FloatBarrier

The column labeled Assignment 3 shows the assignment that actually
occurred. The other possible assignments --- Assignment 1, Assignment 2,
and Assignment 4 --- represent cases in which Lesotho, Somalia, or
Burundi is treated instead of Rwanda. The set excludes any assignments
with more than \(1\) treated unit.

The set of possible treatment assignments across all matched sets, given
the number treated in each, is
\(\Omega = \Omega_1 \times \ldots \times \Omega_S\), which is all the
ways one assignment can be chosen from each \(\Omega_s\) at the same
time. Although the assignment itself can vary, the underlying causal
quantities of interest --- \(\bm{\tau}\) and \(\tau\) --- remain fixed
across all possible assignments. What changes from one assignment to
another is which potential outcomes we would actually observe. In the
observed Assignment 3, we see Rwanda's treated potential outcome and the
control potential outcomes of Burundi, Somalia, and Lesotho, but not
Rwanda's control potential outcome or the treated potential outcomes of
the others. Under a different assignment, a different set of treated and
control potential outcomes would have been observed. No matter which
assignment occurs, we observe only partial information about our causal
targets.

Inference from the partial information contained in the data to our
causal targets is predicated on a probability distribution defined over
the set of assignments, \(\Omega\). This distribution constitutes the
uncertainty underlying our inferences --- what \citet[p.~14]{fisher1935}
famously called the ``reasoned basis'' for inference --- but, unlike in
a randomized experiment, this distribution is unknown in an
observational study. Because this distribution is unknown, we must make
assumptions about it when drawing inferences from observational data.
Under the assumption of as-if randomization, every possible assignment
within each \(\Omega_s\) is equally likely, making each overall
assignment in \(\Omega\) equally likely as well. In this case, all
individuals within the same matched set have the same probability of
treatment, equal to \(m_s / n_s\). When as-if randomization does not
hold, however, assignments are no longer equally likely, and some
individuals have a higher probability of treatment than others.

\subsubsection{How Do I Draw Inferences under the Sharp
Framework?}\label{how-do-i-draw-inferences-under-the-sharp-framework}

To set the stage for inference under the sharp framework, consider a
thought experiment. Suppose we were to subtract the true individual
effects from the outcomes of whichever units happen to be treated. Doing
so would yield, for each unit, the outcome it would have had under
control. In other words, we may imagine reconstructing the dataset so
that, under any possible treatment assignment, the outcomes would appear
exactly as they would have if no one had been treated. In this
reconstructed world, there would be no effect since every unit's outcome
would reflect what it would have been without treatment.

Of course, we do not know the true collection of individual effects,
\(\bm{\tau}\), but we can test hypotheses about it, such as the
hypothesis of a homogeneous effect for all units, denoted by \(\tau_h\).
We do so by evaluating whether the data would look consistent with no
treatment effect when that hypothesized value is subtracted from the
treated outcomes. If, after this reconstruction, the data still show a
positive effect, then the hypothesized value is presumably too small; if
they show a negative effect, then the hypothesized value is presumably
too large.

From a hypothesis testing perspective, when outcomes are reconstructed
under a null hypothesis, the observed test statistic --- computed on
these reconstructed outcomes --- will tend to fall in the upper tail of
the null distribution if the hypothesized effect is too small, and in
the lower tail if it is too large. To generate this null distribution,
we reconstruct the outcomes under the hypothesized effect. Under the
null, these reconstructed outcomes would remain fixed across
assignments, so we hold them constant and recalculate the test statistic
for every possible assignment. We then use this null distribution to
determine where the observed test statistic falls for the calculation of
\(p\)-values.

A canonical choice of test statistic in this setting is a \emph{sum
statistic}, which first adds up the treated outcomes within each set,
and then adds those set-level sums across all sets. Many familiar test
statistics can be expressed in this form by applying to the outcomes
scale and shift transformations that do not depend on the treatment
assignments. One such useful test statistic that can be expressed as a
sum statistic is the Difference-in-Means, computed within sets and then
averaged across sets, with each set's contribution weighted by its
effective sample size.

Under as-if randomization, the harmonic-mean-weighted
Difference-in-Means is useful because, as discussed earlier, the
variance of the within-set Difference-in-Means is minimized --- under
homogeneous treatment effects --- when the harmonic mean of the numbers
of treated and control units is largest. As a result, under this model
of homogeneous individual treatment effects, a test has greater power
when it places more weight on sets with large harmonic means --- that
is, sets in which the Difference-in-Means is most informative. Weighting
sets solely by their share of units, by contrast, can overweight large
but highly lopsided sets and dilute information from more balanced
comparisons.

The harmonic-mean--weighted Difference-in-Means also has the practical
advantage of coinciding with two other common approaches to analyzing
matched data:

\begin{itemize}
\item
  First, the harmonic-mean--weighted Difference-in-Means equals the
  coefficient on the treatment indicator from a fixed-effects regression
  that includes matched set indicators
  \citep[pp.~228-229]{hansenbowers2008}, an approach commonly used in
  practice after matching.
\item
  Second, the harmonic-mean--weighted Difference-in-Means coincides with
  the overlap-weighted Difference-in-Means \citep{lietal2018} when
  overlap weights are constructed using the treatment assignment
  probabilities implied by as-if randomization. Overlap weights place
  the greatest weight on units with intermediate values of these
  assignment probabilities and downweight units with extreme values. In
  particular, using the assignment probability under as-if
  randomization, control units are weighted by that probability, while
  treated units are weighted by \(1\) minus that probability. Because
  these assignment probabilities are constant within each matched set,
  the resulting overlap weights are constant within treated units and
  within control units in a set, and they aggregate exactly to the
  harmonic-mean weights implied by the matched sets.
\end{itemize}

To implement a sum statistic equivalent to the harmonic-mean--weighted
Difference-in-Means for hypothesis testing, we first reconstruct the
outcomes that treated units would have exhibited under the null
hypothesis \(\tau_h = 0\).

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Keep only rows assigned to a matched set (drop NA in fm)}
\NormalTok{data\_matched }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(}
  \AttributeTok{.data =}\NormalTok{ data, }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(fm)}
\NormalTok{)}

\CommentTok{\# Null hypothesis value}
\NormalTok{tau\_h }\OtherTok{\textless{}{-}} \DecValTok{0}

\CommentTok{\# Reconstruct outcomes under sharp null (tau\_h = 0)}
\NormalTok{data\_matched }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{ldur\_tilde =}\NormalTok{ ldur }\SpecialCharTok{{-}}\NormalTok{ tau\_h }\SpecialCharTok{*}\NormalTok{ UN}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\doublespacing

We now source a helper function from the companion GitHub repository;
this function rescales the outcome variable so that the sum of the
rescaled values among treated units equals the harmonic-mean--weighted
Difference-in-Means. After sourcing the function, we apply it to the
matched dataset to generate a new column containing the rescaled
outcomes. We then use this rescaled outcome to compute the observed test
statistic.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load hm\_stat\_rescale() from GitHub repo}
\CommentTok{\# base\_url (defined earlier) points to repo URL}
\FunctionTok{source}\NormalTok{(}
  \FunctionTok{paste0}\NormalTok{(}
\NormalTok{    base\_url, }\StringTok{"/R/hm\_stat\_rescale.R"}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# Apply rescaling: adds .hm\_scaled and returns matched dataset}
\NormalTok{data\_matched }\OtherTok{\textless{}{-}} \FunctionTok{hm\_stat\_rescale}\NormalTok{(}
  \AttributeTok{data =}\NormalTok{ data\_matched,}
  \AttributeTok{outcome =}\NormalTok{ ldur\_tilde, }\CommentTok{\# Set outcome to be rescaled within matched sets}
  \AttributeTok{treat =}\NormalTok{ UN,           }\CommentTok{\# Set name of treatment indicator variable}
  \AttributeTok{strata =}\NormalTok{ fm           }\CommentTok{\# Set name of matched strata (block) variable}
\NormalTok{)}

\CommentTok{\# Observed HM{-}weighted diff{-}in{-}means statistic}
\NormalTok{obs\_stat }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}
\NormalTok{  data\_matched}\SpecialCharTok{$}\NormalTok{ldur\_tilde\_hm\_scaled[data\_matched}\SpecialCharTok{$}\NormalTok{UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

We can verify in \texttt{R} that this observed sum statistic coincides
with the harmonic-mean-weighted Difference-in-Means, the coefficient on
the treatment indicator from a fixed-effects regression that includes
matched set indicators, and the overlap-weighted Difference-in-Means
constructed from the assignment probabilities implied by as-if
randomization.

First, we show that the observed sum statistic equals the
harmonic-mean--weighted average of the within--matched-set
Differences-in-Means, where each matched set is weighted by its
contribution to the effective sample size.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Harmonic{-}mean{-}weighted difference in means (weights computed within sets)}
\NormalTok{dim\_hm }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(}
\NormalTok{    fm}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{n\_treated =} \FunctionTok{sum}\NormalTok{(UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{),}
    \AttributeTok{n\_control =} \FunctionTok{sum}\NormalTok{(UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{),}
    \CommentTok{\# Within{-}set Difference{-}in{-}Means}
    \AttributeTok{dim\_set   =} \FunctionTok{mean}\NormalTok{(ldur\_tilde[UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]) }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(ldur\_tilde[UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{]),}
    \CommentTok{\# Harmonic{-}mean weight (set\textquotesingle{}s contribution to effective sample size)}
    \AttributeTok{w\_hm      =} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ n\_treated }\SpecialCharTok{*}\NormalTok{ n\_control }\SpecialCharTok{/}\NormalTok{ (n\_treated }\SpecialCharTok{+}\NormalTok{ n\_control),}
    \AttributeTok{.groups   =} \StringTok{"drop"} \CommentTok{\# Drop grouping after summarise}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarize}\NormalTok{(}
    \CommentTok{\# Harmonic{-}mean{-}weighted average of within{-}set Differences{-}in{-}Means}
    \AttributeTok{dim\_hm =} \FunctionTok{sum}\NormalTok{(}
\NormalTok{      w\_hm }\SpecialCharTok{*}\NormalTok{ dim\_set) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(w\_hm)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pull}\NormalTok{( }\CommentTok{\# Pull column out of data frame}
\NormalTok{    dim\_hm}
\NormalTok{  )}

\CommentTok{\# Approaches coincides with the sum statistic}
\FunctionTok{all.equal}\NormalTok{(}
\NormalTok{  dim\_hm, obs\_stat}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] TRUE
\end{verbatim}

\doublespacing

Next, we verify that the same quantity is obtained as the coefficient on
the treatment indicator from a fixed-effects regression that includes
matched set indicators.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# FE coefficient on UN (matched{-}set FE)}
\NormalTok{fe\_fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}
  \AttributeTok{formula =}\NormalTok{ ldur\_tilde }\SpecialCharTok{\textasciitilde{}}\NormalTok{ UN }\SpecialCharTok{+}\NormalTok{ fm,}
  \AttributeTok{data =}\NormalTok{ data\_matched}
\NormalTok{)}

\CommentTok{\# Drop name so comparison is purely numeric}
\NormalTok{treat\_coef\_fe\_fit }\OtherTok{\textless{}{-}} \FunctionTok{unname}\NormalTok{(}
  \FunctionTok{coef}\NormalTok{(fe\_fit)[}\StringTok{"UN"}\NormalTok{]}
\NormalTok{)}

\CommentTok{\# Approaches coincides with the sum statistic}
\FunctionTok{all.equal}\NormalTok{(}
\NormalTok{  treat\_coef\_fe\_fit, obs\_stat}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] TRUE
\end{verbatim}

\doublespacing

Finally, we confirm that the observed sum statistic also coincides with
the overlap-weighted Difference-in-Means. The overlap weights are
constructed from the treatment assignment probabilities implied by as-if
randomization within matched sets, with treated units weighted by one
minus their treatment probability and control units weighted by their
treatment probability.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install "PSweight" package (only run if not already installed)}
\CommentTok{\# install.packages("PSweight")}
\FunctionTok{library}\NormalTok{(PSweight) }\CommentTok{\# For overlap weights from Li et al (2018)}

\CommentTok{\# Treatment probabilities within matched sets: n\_treated / n}
\NormalTok{ps\_fit }\OtherTok{\textless{}{-}} \FunctionTok{PSmethod}\NormalTok{(}
  \AttributeTok{ps.formula =}\NormalTok{ UN }\SpecialCharTok{\textasciitilde{}} \FunctionTok{factor}\NormalTok{(fm), }\CommentTok{\# Reproduces n\_treated / n in each set}
  \AttributeTok{method     =} \StringTok{"glm"}\NormalTok{,           }\CommentTok{\# Estimate using generalized linear model}
  \CommentTok{\# Use as.data.frame() for PSmethod() compatibility}
  \AttributeTok{data       =} \FunctionTok{as.data.frame}\NormalTok{(data\_matched),}
  \AttributeTok{ncate      =} \DecValTok{2}                \CommentTok{\# Binary treatment (treated vs. control)}
\NormalTok{)}

\NormalTok{assign\_prob }\OtherTok{\textless{}{-}}\NormalTok{ ps\_fit}\SpecialCharTok{$}\NormalTok{e.h[, }\StringTok{"1"}\NormalTok{]  }\CommentTok{\# Column for treatment level "1"}

\CommentTok{\# Overlap weights from treatment probabilities}
\CommentTok{\# Controls: treatment probability ; Treated: 1 {-} treatment probability}
\NormalTok{w\_ow }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
  \AttributeTok{test =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{,}
  \AttributeTok{yes  =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ assign\_prob,}
  \AttributeTok{no   =}\NormalTok{ assign\_prob}
\NormalTok{)}

\CommentTok{\# Overlap{-}weighted difference in means}
\NormalTok{dim\_ow }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarize}\NormalTok{( }\CommentTok{\# Aggregate rows into summary values}
    \CommentTok{\# Overlap{-}weighted mean outcome for treated units}
    \AttributeTok{treated\_weighted\_mean =}
      \FunctionTok{sum}\NormalTok{(w\_ow[UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{] }\SpecialCharTok{*}\NormalTok{ ldur\_tilde[UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(w\_ow[UN }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]),}

    \CommentTok{\# Overlap{-}weighted mean outcome for control units}
    \AttributeTok{control\_weighted\_mean =}
      \FunctionTok{sum}\NormalTok{(w\_ow[UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{] }\SpecialCharTok{*}\NormalTok{ ldur\_tilde[UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{]) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(w\_ow[UN }\SpecialCharTok{==} \DecValTok{0}\NormalTok{]),}

    \CommentTok{\# Difference between overlap{-}weighted treated and control means}
    \AttributeTok{dim\_ow =}\NormalTok{ treated\_weighted\_mean }\SpecialCharTok{{-}}\NormalTok{ control\_weighted\_mean}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pull}\NormalTok{(}
\NormalTok{    dim\_ow}
\NormalTok{  )}

\CommentTok{\# Approaches coincides with the sum statistic}
\FunctionTok{all.equal}\NormalTok{(}
\NormalTok{  dim\_ow, obs\_stat}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] TRUE
\end{verbatim}

\doublespacing

Now, to generate the distribution to which we refer our observed sum
statistic, we can hold the reconstructed and rescaled outcomes fixed and
then calculate the sum statistic over all possible assignments in
\(\Omega\). In our application, with 12 sets ranging in size from 2 to
5, the total number of assignments is 311,040.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# For each matched set (fm), record:}
\CommentTok{\# n = total units in the set}
\CommentTok{\# m = number treated (UN == 1)}
\NormalTok{block\_ns }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(          }\CommentTok{\# Group results by key variables}
\NormalTok{    fm}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(         }\CommentTok{\# Aggregate to one row per group}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),         }\CommentTok{\# Row count per group}
    \AttributeTok{m =} \FunctionTok{sum}\NormalTok{(UN),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\CommentTok{\# Total possible treatment assignments = product of binomial coefficients}
\CommentTok{\# (choose n\_s units for treatment in each set and multiply across sets)}
\NormalTok{exact\_n\_assigns }\OtherTok{\textless{}{-}} \FunctionTok{prod}\NormalTok{(}
  \FunctionTok{choose}\NormalTok{(}
    \AttributeTok{n =}\NormalTok{ block\_ns}\SpecialCharTok{$}\NormalTok{n,}
    \AttributeTok{k =}\NormalTok{ block\_ns}\SpecialCharTok{$}\NormalTok{m}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Because our matched study is relatively small, we can enumerate all
possible treatment assignments exactly.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install "randomizr" (only run if not already installed)}
\CommentTok{\# install.packages("randomizr")}

\CommentTok{\# Load randomizr for generating random assignments}
\FunctionTok{library}\NormalTok{(randomizr)}

\NormalTok{exact\_assigns }\OtherTok{\textless{}{-}} \FunctionTok{obtain\_permutation\_matrix}\NormalTok{(}
  \AttributeTok{declaration =} \FunctionTok{declare\_ra}\NormalTok{(   }\CommentTok{\# Declare assignment procedure}
    \AttributeTok{N =} \FunctionTok{nrow}\NormalTok{(data\_matched),   }\CommentTok{\# Total number of units}
    \AttributeTok{blocks =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{fm, }\CommentTok{\# Matched set membership}
    \AttributeTok{block\_m =}\NormalTok{ block\_ns}\SpecialCharTok{$}\NormalTok{m      }\CommentTok{\# Number treated in each set}
\NormalTok{  ),}
\CommentTok{\# Total number of assignments with treated counts fixed within sets}
  \AttributeTok{maximum\_permutations =}\NormalTok{ exact\_n\_assigns}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

However, in most applications, exactly enumerating all possible
assignments is computationally infeasible. Instead, we typically draw a
random subset of assignments (e.g., \(10{,}000\)) to approximate the
exact randomization distribution, as illustrated below.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set RNG seed for reproducibility}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{11242017}\NormalTok{)}

\CommentTok{\# Generate permutation matrix of treatment assignments}
\CommentTok{\# Each column = one possible assignment consistent with block structure}
\NormalTok{sim\_assigns }\OtherTok{\textless{}{-}} \FunctionTok{obtain\_permutation\_matrix}\NormalTok{(}
  \AttributeTok{declaration =} \FunctionTok{declare\_ra}\NormalTok{(}
    \AttributeTok{N =} \FunctionTok{nrow}\NormalTok{(data\_matched),}
    \AttributeTok{blocks =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{fm,}
    \AttributeTok{block\_m =}\NormalTok{ block\_ns}\SpecialCharTok{$}\NormalTok{m}
\NormalTok{  ),}
  \AttributeTok{maximum\_permutations =} \DecValTok{10}\SpecialCharTok{\^{}}\DecValTok{4}  \CommentTok{\# Cap at 10,000 random draws}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Now, to generate the null distribution of the sum statistic, we apply
the statistic to each of these \(10{,}000\) assignments while holding
the reconstructed and rescaled outcomes fixed under the null.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Randomization distribution under sharp null}
\CommentTok{\# Apply sum statistic to each assignment in sim\_assigns}
\CommentTok{\# Outcome transformed so sum = harmonic{-}mean weighted diff in means}
\NormalTok{sim\_sharp\_null\_dist }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(}
  \AttributeTok{X =}\NormalTok{ sim\_assigns,    }\CommentTok{\# Matrix of treatment assignments}
  \AttributeTok{MARGIN =} \DecValTok{2}\NormalTok{,         }\CommentTok{\# Iterate over columns (assignments)}
  \AttributeTok{FUN =} \ControlFlowTok{function}\NormalTok{(x) \{}
    \CommentTok{\# Sum transformed outcomes among treated}
    \FunctionTok{sum}\NormalTok{(}
\NormalTok{      data\_matched}\SpecialCharTok{$}\NormalTok{ldur\_tilde\_hm\_scaled[x }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]}
\NormalTok{    )}
\NormalTok{  \}}
\NormalTok{)}
\CommentTok{\# Faster equivalent computation via matrix multiplication}
\CommentTok{\# as.numeric(}
\CommentTok{\#   t(data\_matched$ldur\_tilde\_hm\_scaled) \%*\% sim\_assigns}
\CommentTok{\# )}
\end{Highlighting}
\end{Shaded}

\doublespacing

From this null distribution, we compute a one-sided upper \(p\)-value,
which, under as-if randomization, is simply the proportion of null test
statistics greater than or equal to the observed test statistic.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# One{-}sided, upper p{-}value:}
\CommentTok{\# Propprtion of simulated randomization stats \textgreater{}= observed}
\FunctionTok{round}\NormalTok{(}
  \AttributeTok{x =} \FunctionTok{mean}\NormalTok{(}
\NormalTok{    sim\_sharp\_null\_dist }\SpecialCharTok{\textgreater{}=}\NormalTok{ obs\_stat}
\NormalTok{  ),}
  \AttributeTok{digits =} \DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.0346
\end{verbatim}

\doublespacing

The upper \(p\)-value of a test of the sharp null of no effect against
the alternative of a larger effect is 0.0346.

In this particular case, unlike in most applications, the matched study
is small enough to compute the exact \(p\)-value and assess the accuracy
of the simulation-based \(p\)-value approximation.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Transformed outcomes under sharp null (tau\_h = 0)}
\NormalTok{q\_tau\_h\_0 }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{ldur\_tilde\_hm\_scaled}

\CommentTok{\# Fast computation of exact null distribution using matrix multiplication}
\NormalTok{exact\_sharp\_null\_dist }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{t}\NormalTok{(q\_tau\_h\_0) }\SpecialCharTok{\%*\%}\NormalTok{ exact\_assigns}
\NormalTok{)}

\CommentTok{\# Slower apply(){-}based computation (for reference)}
\CommentTok{\# apply(}
\CommentTok{\#  X = exact\_assigns,}
\CommentTok{\#  MARGIN = 2,}
\CommentTok{\#  FUN = function(x) \{}
\CommentTok{\#    sum(data\_matched$ldur\_tilde\_hm\_scaled[x == 1])}
\CommentTok{\#  \}}
\CommentTok{\#)}

\CommentTok{\# Exact one{-}sided, upper p{-}value}
\FunctionTok{round}\NormalTok{(}
  \AttributeTok{x =} \FunctionTok{mean}\NormalTok{(}
\NormalTok{    exact\_sharp\_null\_dist }\SpecialCharTok{\textgreater{}=}\NormalTok{ obs\_stat}
\NormalTok{  ),}
  \AttributeTok{digits =} \DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.0363
\end{verbatim}

\doublespacing

The exact \(p\)-value of 0.0363 is nearly identical to the
simulation-based \(p\)-value of 0.0346. At the conventional significance
level of \(\alpha = 0.05\), we would reject the null hypothesis in favor
of the alternative, regardless of whether we use the exact or
simulation-based \(p\)-value.

As an alternative to randomly sampling assignments and computing the
test statistic for each one, we can use a much faster Normal
approximation to the null distribution when the matched study is
sufficiently large. The approximation relies on closed-form expressions
for the expected value and variance of a sum statistic derived in
\citet{rosenbaumkrieger1990}. Using these expressions, we standardize
the observed test statistic and then compare it to the standard Normal
distribution, which gives us a corresponding \(p\)-value. Although
primarily designed for sensitivity analyses under violations of as-if
randomization, the \texttt{senstrat} package can also be used to compute
the null expected value and variance of a sum statistic under as-if
randomization.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install "senstrat" package (only run if not already installed)}
\CommentTok{\# install.packages("senstrat")}

\CommentTok{\# Load senstrat for stratum{-}level null moments and sensitivity analysis}
\CommentTok{\# (Rosenbaum \& Krieger 1990)}
\FunctionTok{library}\NormalTok{(senstrat)}

\CommentTok{\# Compute per{-}block null expectations and variances}
\NormalTok{per\_block\_moms }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(}
\NormalTok{    fm}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{expect   =} \FunctionTok{ev}\NormalTok{(}
      \AttributeTok{sc =}\NormalTok{ ldur\_tilde\_hm\_scaled, }\CommentTok{\# Transformed outcomes for the stratum}
      \AttributeTok{z =}\NormalTok{ UN,                    }\CommentTok{\# Treatment indicator}
      \AttributeTok{m =} \DecValTok{1}\NormalTok{,                     }\CommentTok{\# Count of 1s in hidden confounder}
                                 \CommentTok{\# Irrelevant here since Gamma = 1}
      \AttributeTok{g =} \DecValTok{1}\NormalTok{,                     }\CommentTok{\# Sensitivity parameter Gamma}
      \AttributeTok{method =} \StringTok{"RK"}              \CommentTok{\# Use Rosenbaum and Krieger (1990) formula }
\NormalTok{    )}\SpecialCharTok{$}\NormalTok{expect,                    }\CommentTok{\# Null expectation of sum statistic by set}
    \AttributeTok{variance =} \FunctionTok{ev}\NormalTok{(}
      \AttributeTok{sc     =}\NormalTok{ ldur\_tilde\_hm\_scaled,}
      \AttributeTok{z      =}\NormalTok{ UN,}
      \AttributeTok{m =} \DecValTok{1}\NormalTok{,}
      \AttributeTok{g      =} \DecValTok{1}\NormalTok{,}
      \AttributeTok{method =} \StringTok{"RK"}
\NormalTok{    )}\SpecialCharTok{$}\NormalTok{vari,                      }\CommentTok{\# Null variance of sum statistic by set}
    \AttributeTok{.groups  =} \StringTok{"drop"}
\NormalTok{  )}

\CommentTok{\# Sum across blocks to get overall null expectation}
\NormalTok{null\_ev  }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}
\NormalTok{  per\_block\_moms}\SpecialCharTok{$}\NormalTok{expect}
\NormalTok{)}

\CommentTok{\# Sum across blocks to get overall null variance}
\NormalTok{null\_var }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}
\NormalTok{  per\_block\_moms}\SpecialCharTok{$}\NormalTok{variance}
\NormalTok{)}

\CommentTok{\# Standardized test statistic and one{-}sided Normal p{-}value (upper tail)}
\NormalTok{norm\_upper\_p\_value }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(}
  \AttributeTok{q =}\NormalTok{ (obs\_stat }\SpecialCharTok{{-}}\NormalTok{ null\_ev) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(null\_var), }\CommentTok{\# Standardized statistic}
  \AttributeTok{lower.tail =} \ConstantTok{FALSE}                         \CommentTok{\# Compute upper{-}tail prob}
\NormalTok{)}
\CommentTok{\# By default in pnorm(): mean = 0 and sd = 1 (standard normal distribution)}
\end{Highlighting}
\end{Shaded}

\doublespacing

This Normal-approximation \(p\)-value of 0.0343 is close to the exact
and simulation-based \(p\)-values of 0.0363 and 0.0346, respectively.
All \(p\)-values lead to the same conclusion in which we reject the
sharp null of no effect in favor of a larger effect.

To test not just a single null hypothesis but a grid of null hypotheses
under the sharp null framework, we use a Normal approximation to the
randomization distribution. We repeat the above procedure for a range of
hypothesized constant effects, \(\tau_h\). For each value of \(\tau_h\),
we reconstruct the outcomes under the null, rescale them so that the sum
statistic equals the harmonic-mean--weighted Difference-in-Means,
compute the observed test statistic, and obtain the corresponding
p-value using the Normal approximation. To form a one-sided confidence
set, we retain all null values that are not rejected by the upper-tail
test at the chosen \(\alpha\) level. To form a two-sided confidence set,
we proceed analogously, allocating \(\alpha/2\) to each tail ---
reflecting that each null value is tested against departures in both
directions --- and using the corresponding upper- and lower-tail
rejection regions.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Significance level}
\NormalTok{alpha }\OtherTok{\textless{}{-}} \FloatTok{0.05}

\CommentTok{\# Upper{-}tail confidence set (tau\_h values not rejected by upper{-}tail test)}
\CommentTok{\# Lower endpoint: smallest tau\_h with upper{-}tail p{-}value \textgreater{}= alpha}
\CommentTok{\# (any smaller tau\_h would be rejected)}
\NormalTok{cs\_sharp\_lower\_one\_sided }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \AttributeTok{lower =}\NormalTok{ obs\_stat }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(null\_var),}
  \AttributeTok{upper =} \ConstantTok{Inf}
\NormalTok{)}
\CommentTok{\# qnorm(1 {-} alpha): upper one{-}sided Normal critical value}

\NormalTok{cs\_sharp\_two\_sided }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \AttributeTok{lower =}\NormalTok{ obs\_stat }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(null\_var),}
  \AttributeTok{upper =}\NormalTok{ obs\_stat }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(null\_var)}
\NormalTok{)}
\CommentTok{\# At lower endpoint, upper{-}tail one{-}sided p{-}value equals alpha/2;}
\CommentTok{\# any smaller null value would be rejected by two{-}sided test}
\CommentTok{\# At upper endpoint, lower{-}tail one{-}sided p{-}value equals alpha/2;}
\CommentTok{\# any larger null value would be rejected by two{-}sided test}
\end{Highlighting}
\end{Shaded}

\doublespacing

An analogous procedure applies when constructing confidence sets without
relying on a Normal approximation, instead using a simulation-based
approximation to the null randomization distribution.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Grid of constant{-}effect null values (sharp framework)}
\NormalTok{tau\_h\_grid }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}
  \AttributeTok{from =} \SpecialCharTok{{-}}\FloatTok{0.02}\NormalTok{,}
  \AttributeTok{to =} \FloatTok{1.5}\NormalTok{,}
  \AttributeTok{by =} \FloatTok{0.0001}
\NormalTok{)}

\CommentTok{\# Repeat the randomization test for each tau\_h}
\CommentTok{\# sapply() computes and stacks the resulting p{-}values}
\NormalTok{p\_mat }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(}\AttributeTok{X =}\NormalTok{ tau\_h\_grid,}
                \AttributeTok{FUN =} \ControlFlowTok{function}\NormalTok{(tau\_h) \{}

                  \CommentTok{\# Shift outcomes under null: ldur\_i {-} tau\_h * UN\_i}
\NormalTok{                  dat\_tau\_h }\OtherTok{\textless{}{-}} \FunctionTok{hm\_stat\_rescale}\NormalTok{(}
                  \CommentTok{\# transform(): copy data\_matched adding shifted outcome}
                    \AttributeTok{data    =} \FunctionTok{transform}\NormalTok{(}
\NormalTok{                      data\_matched,}
                      \AttributeTok{ldur\_tilde\_shift =}\NormalTok{ ldur }\SpecialCharTok{{-}}\NormalTok{ tau\_h }\SpecialCharTok{*}\NormalTok{ UN),}
                    \AttributeTok{outcome =}\NormalTok{ ldur\_tilde\_shift,}
                    \AttributeTok{treat   =}\NormalTok{ UN,}
                    \AttributeTok{strata  =}\NormalTok{ fm}
\NormalTok{                  )}

                  \CommentTok{\# Transformed outcomes under sharp null tau\_h}
\NormalTok{                  q\_tau\_h }\OtherTok{\textless{}{-}}\NormalTok{ dat\_tau\_h}\SpecialCharTok{$}\NormalTok{ldur\_tilde\_shift\_hm\_scaled}

                  \CommentTok{\# Observed statistic under null tau\_h}
\NormalTok{                  obs\_stat\_tau\_h }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}
\NormalTok{                    dat\_tau\_h}\SpecialCharTok{$}\NormalTok{UN }\SpecialCharTok{*}\NormalTok{ q\_tau\_h}
\NormalTok{                  )}

                  \CommentTok{\# Randomization distribution via simulated assignments}
                  \CommentTok{\# Matrix multiplication used for speed (vs apply())}
\NormalTok{                  sim\_null\_dist\_tau\_h }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
                    \FunctionTok{t}\NormalTok{(q\_tau\_h) }\SpecialCharTok{\%*\%}\NormalTok{ sim\_assigns}
\NormalTok{                  )}

                  \CommentTok{\# Upper{-}tail and lower{-}tail randomization p{-}values}
\NormalTok{                  p\_upper\_tau\_h }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}
\NormalTok{                    sim\_null\_dist\_tau\_h }\SpecialCharTok{\textgreater{}=}\NormalTok{ obs\_stat\_tau\_h}
\NormalTok{                  )}

\NormalTok{                  p\_lower\_tau\_h }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}
\NormalTok{                    sim\_null\_dist\_tau\_h }\SpecialCharTok{\textless{}=}\NormalTok{ obs\_stat\_tau\_h}
\NormalTok{                  )}

                  \FunctionTok{c}\NormalTok{(}
                    \AttributeTok{upper\_tail =}\NormalTok{ p\_upper\_tau\_h,}
                    \AttributeTok{lower\_tail =}\NormalTok{ p\_lower\_tau\_h}
\NormalTok{                  )}
\NormalTok{                \})}

\CommentTok{\# Extract vector of upper{-}tail p{-}values}
\NormalTok{p\_upper }\OtherTok{\textless{}{-}}\NormalTok{ p\_mat[}\StringTok{"upper\_tail"}\NormalTok{, ]}

\CommentTok{\# Extract vector of lower{-}tail p{-}values}
\NormalTok{p\_lower }\OtherTok{\textless{}{-}}\NormalTok{ p\_mat[}\StringTok{"lower\_tail"}\NormalTok{, ]}

\CommentTok{\# Simulation{-}based confidence sets}

\CommentTok{\# Upper{-}tail confidence set: retain all tau\_h with upper{-}tail p \textgreater{}= alpha}
\NormalTok{cs\_sharp\_upper\_tail\_sim }\OtherTok{\textless{}{-}}\NormalTok{ tau\_h\_grid[p\_upper }\SpecialCharTok{\textgreater{}=}\NormalTok{ alpha]}

\CommentTok{\# Lower bound of the upper{-}tail confidence set}
\NormalTok{cs\_sharp\_upper\_tail\_sim\_bound }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}
\NormalTok{  cs\_sharp\_upper\_tail\_sim}
\NormalTok{)}

\CommentTok{\# Two{-}sided confidence set (inversion using alpha/2 in each tail):}
\CommentTok{\# retain tau\_h only if neither one{-}sided test rejects at level alpha/2}
\NormalTok{cs\_sharp\_two\_sided\_sim }\OtherTok{\textless{}{-}}\NormalTok{ tau\_h\_grid[}
\NormalTok{  p\_upper }\SpecialCharTok{\textgreater{}=}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2} \SpecialCharTok{\&}\NormalTok{ p\_lower }\SpecialCharTok{\textgreater{}=}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2}
\NormalTok{]}

\CommentTok{\# Two{-}sided confidence set summarized by its bounds}
\NormalTok{cs\_sharp\_two\_sided\_sim\_bounds }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \AttributeTok{lower =} \FunctionTok{min}\NormalTok{(}
\NormalTok{    cs\_sharp\_two\_sided\_sim}
\NormalTok{  ),}
  \AttributeTok{upper =} \FunctionTok{max}\NormalTok{(}
\NormalTok{    cs\_sharp\_two\_sided\_sim}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Likewise, for a point estimate, one could follow
\citet{hodgeslehmann1963} and \citet{rosenbaum1993} by identifying the
null value that makes the observed sum statistic equal to its null
expectation. With our test statistic under as-if randomization, this
would occur when the null equals the harmonic-mean weighted
Difference-in-Means computed from the observed outcomes (roughly 0.673),
which yields a null expectation of \(0\).

\subsubsection{How Do I Draw Inferences under the Weak
Framework?}\label{how-do-i-draw-inferences-under-the-weak-framework}

When the target is the ATE, it can be written as
\(\tau = \sum_{s = 1}^S (n_s / n)\tau_s\), a weighted average of the
set-level ATEs with weights equal to each set's share of the total study
size. Thus, a straightforward way to estimate the ATE is to compute the
Difference-in-Means within each matched set, and then combine these
set-level estimates using the same weights. Formally, the overall
Difference-in-Means is
\(\hat{\tau} = \sum_{s=1}^S (n_s / n) \hat{\tau}_s\), where
\(\hat{\tau}_s\) is the Difference-in-Means in set \(s\).

These weights are appealing because, under as-if randomization, the
resulting Difference-in-Means is an unbiased estimator of the ATE.
Formally, the expected value of the estimator --- i.e., the average of
\(\hat{\tau}\) taken over all treatment assignments consistent with the
matched design and their associated probabilities --- equals the true
ATE. Nevertheless, although correct in expectation, the
Difference-in-Means can vary substantially across assignments. In any
given assignment, the estimate may lie far from the target ATE.

Because the estimator can fluctuate across different treatment
assignments, it is important to quantify the typical squared distance
between an estimate and the true ATE. To this end, \citet{neyman1923}
introduced a canonical variance estimator. Under as-if randomization,
this estimator is exactly unbiased when individual treatment effects are
homogeneous; otherwise, it is conservative, meaning its expected value
is greater than or equal to the true variance of the
Difference-in-Means, although subsequent refinements reduce this
conservativeness while maintaining validity
\citep[see][]{robins1988, aronowetal2014, harshawetal2024}. In
principle, we could apply this approach by estimating the variance of
the Difference-in-Means within each matched set and then taking a
weighted sum of these estimates \citep[see, e.g.,][]{miratrixetal2013}.

In our setting, however, this approach is infeasible because each
matched set contains only \(1\) treated or \(1\) control unit. The usual
Neyman formula relies on computing sample variances separately within
the treated and control groups of each set. The sample variance requires
at least two observations because \texttt{var()} divides by the number
of observations minus \(1\). As a result, we cannot compute the sample
variance when there is only a single treated or control unit.

How, then, can we estimate the variance of the Difference-in-Means in a
matched observational study? \citet{pashleymiratrix2021} and
\citet{fogarty2018} offer distinct solutions.
\citet{pashleymiratrix2021} propose two approaches, each valid under
different conditions on the matched structure, while \citet{fogarty2018}
develops a single method that applies more broadly to finely stratified
designs.

The first approach in \citet{pashleymiratrix2021}, \texttt{hybrid\_m},
requires at least two matched sets of each unique set size in the data.
The second approach, \texttt{hybrid\_p}, permits variation in set sizes
as long as no single set contains half or more of the total study size.
Our matched design meets the condition for the second approach, not the
first. We therefore estimate the variance using \texttt{hybrid\_p}
through the \texttt{blkvar} package, the companion software for
\citet{pashleymiratrix2021}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install blkvar (only run if not already installed)}
\CommentTok{\# install.packages("remotes")}
\CommentTok{\# Remotes::install\_github("lmiratrix/blkvar")}

\CommentTok{\# Load blkvar for block randomization variance estimators}
\FunctionTok{library}\NormalTok{(blkvar)}

\CommentTok{\# Compute results with hybrid\_p method}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{block\_estimator}\NormalTok{(}
  \AttributeTok{Yobs =}\NormalTok{ ldur,         }\CommentTok{\# Observed outcomes}
  \AttributeTok{Z =}\NormalTok{ UN,              }\CommentTok{\# Treatment indicator}
  \AttributeTok{B =}\NormalTok{ fm,              }\CommentTok{\# Block (matched set) membership}
  \AttributeTok{data =}\NormalTok{ data\_matched, }\CommentTok{\# Dataset}
  \AttributeTok{method =} \StringTok{"hybrid\_p"}  \CommentTok{\# variance estimation method}
\NormalTok{)}

\CommentTok{\# Extract variance estimate}
\NormalTok{res}\SpecialCharTok{$}\NormalTok{var\_est}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.1187282
\end{verbatim}

\doublespacing

We can also estimate the variance of the Difference-in-Means in a finely
stratified design using the approach of \citet{fogarty2018}. To do so,
we load a custom \texttt{R} function, \texttt{fine\_strat\_var\_est()},
from the companion GitHub repository.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the fine\_strat\_var\_est() function from the GitHub repo}
\FunctionTok{source}\NormalTok{(}
  \FunctionTok{paste0}\NormalTok{(}
\NormalTok{    base\_url, }\StringTok{"/R/fine\_strat\_var\_est.R"}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

The function takes as inputs the set-specific treatment effect estimates
and the number of units in each set, and it returns a single scalar
representing the estimated variance. We compute the set-specific
estimates and corresponding set sizes, and then pass these two vectors
as inputs to \texttt{fine\_strat\_var\_est()}.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute matched set sizes and matched{-}set{-}specific differences in means}
\NormalTok{set\_stats }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(}
\NormalTok{    fm}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),                              }\CommentTok{\# Matched set size}
    \AttributeTok{diff\_in\_means =} \FunctionTok{mean}\NormalTok{(                 }\CommentTok{\# Treated mean}
\NormalTok{      ldur[UN }\SpecialCharTok{==} \DecValTok{1}\DataTypeTok{L}\NormalTok{]}
\NormalTok{    ) }\SpecialCharTok{{-}}                                   \CommentTok{\# minus}
      \FunctionTok{mean}\NormalTok{(                               }\CommentTok{\# control mean}
\NormalTok{        ldur[UN }\SpecialCharTok{==} \DecValTok{0}\DataTypeTok{L}\NormalTok{]}
\NormalTok{      ),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\CommentTok{\# Apply Fogarty (2018/2023) variance estimator}
\FunctionTok{fine\_strat\_var\_est}\NormalTok{(}
  \AttributeTok{strat\_ns =}\NormalTok{ set\_stats}\SpecialCharTok{$}\NormalTok{n,               }\CommentTok{\# Vector of stratum sizes}
  \AttributeTok{strat\_ests =}\NormalTok{ set\_stats}\SpecialCharTok{$}\NormalTok{diff\_in\_means  }\CommentTok{\# Vector of stratum estimates}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.1163934
\end{verbatim}

\doublespacing

This variance estimate is nearly identical to the one we obtained using
the \texttt{hybrid\_p} approach of \citet{pashleymiratrix2021}.

Now that we have estimates of both the ATE and the variance of the ATE
estimator, we can form a standardized test statistic by subtracting the
expected Difference-in-Means implied by the null and dividing the result
by the estimated standard error (the square root of the estimated
variance). We then compare this statistic to a standard Normal
distribution to calculate \(p\)-values. Below, we calculate the upper
one-sided \(p\)-value for a test the null hypothesis that the ATE is
\(0\) against the alternative that it is positive.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}
  \AttributeTok{q =}\NormalTok{ (res}\SpecialCharTok{$}\NormalTok{ATE\_hat }\SpecialCharTok{{-}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{var\_est),}
  \AttributeTok{lower.tail =} \ConstantTok{FALSE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.03722157
\end{verbatim}

\doublespacing

Here, we reject the weak null hypothesis that the ATE equals \(0\) in
favor of the alternative that the ATE is greater than \(0\), using the
conventional significance level of \(\alpha = 0.05\).

As in the construction of confidence sets for a homogeneous treatment
effect under the sharp framework, we form 95\% confidence sets by
inverting the corresponding hypothesis tests. We first construct a
one-sided confidence set obtained by inverting the upper-tail test and
retaining all null values that are not rejected at the \(\alpha = 0.05\)
level. We then construct a two-sided confidence set by allocating
\(\alpha/2 = 0.025\) to each tail, as in the tail allocation used in the
sharp null framework.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# One{-}sided (upper{-}tail) confidence set}
\NormalTok{cs\_weak\_upper\_tail }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \AttributeTok{lower =}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{ATE\_hat }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{var\_est),}
  \AttributeTok{upper =} \ConstantTok{Inf}
\NormalTok{)}

\CommentTok{\# Two{-}sided confidence set}
\NormalTok{cs\_weak\_two\_sided }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \AttributeTok{lower =}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{ATE\_hat }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{var\_est),}
  \AttributeTok{upper =}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{ATE\_hat }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha }\SpecialCharTok{/} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{var\_est)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

\subsection{Third Stage: Sensitivity Analysis (Departures from As-If
Randomization)}\label{third-stage-sensitivity-analysis-departures-from-as-if-randomization}

Up to this point, we have supposed a framework in which each
observation's chance of a UN intervention is like flipping a weighted
coin. Each coin flip is independent across observations, but the
probability of landing tails (i.e., receiving treatment) can differ from
one unit to another depending on its baseline characteristics. With
matching, we make our crucial assumption that all units within a set are
similar enough on these characteristics that their coins have the same
probability of landing tails.

This as-if randomization assumption may fail because of imbalances on
hidden covariates (or residual imbalances on observed covariates, though
the sensitivity analysis to follow subsumes both within the same
framework). To represent such imbalances, consider a single hidden
covariate, \(\bm{u} = (u_{11}, \ldots , u_{Sn_S})^{\top}\), indexed
first by matched set and then by unit within set, with each \(u_{si}\)
constrained to lie in the interval from \(0\) to \(1\). Although the
restriction that each element of \(\bm{u}\) is between 0 and 1 may seem
strong, \citet[p.~300, fn. 33]{rosenbaum2017} shows that any departure
from complete random assignment within blocks can be represented by such
a \(\bm{u}\) in the sense that as-if randomization would hold if we had
access to and exactly matched on this \(\bm{u}\).

\citet{rosenbaum1987a} and \citet{rosenbaumkrieger1990} then propose a
model in which each unit's independent probability of treatment
assignment is given by \begin{equation}
\label{eq: indiv sens prob}
\pi_{si} = \frac{\exp\left[\kappa_s + \log(\Gamma) u_{si}\right]}{1 + \exp\left[\kappa_s + \log(\Gamma) u_{si}\right]}.
\end{equation} The parameter \(\kappa_s\) is a set-specific intercept
that captures the baseline propensity for treatment shared by all units
in matched set \(s\) before accounting for any differences in the hidden
covariate. In other words, \(\kappa_s\) reflects the central idea in
matching that, after forming matched sets homogeneous in observed
covariates, all individuals within a set share the same treatment
propensity based on those covariates. The parameter \(\Gamma \geq 1\),
by contrast, quantifies how strongly the hidden covariate \(u_{si}\) can
alter treatment odds. When \(\Gamma = 1\), all individuals in matched
set \(s\) have the same probability of treatment,
\(\exp[\kappa_s] / (1 + \exp[\kappa_s])\). However, when \(\Gamma > 1\),
two individuals in the same set who differ in the hidden covariate may
differ in their odds of treatment by as much as a factor of \(\Gamma\).

An important point to reiterate is that we condition on assignments that
belong to the set \(\Omega\), meaning that the number of treated units
is fixed within each matched set. It turns out that this conditioning
removes dependence on the set-specific baseline \(\kappa_s\) in the
probability distribution over assignments in \(\Omega\)
\citep{rosenbaum1984}. Eliminating this dependence is crucial because it
allows us to characterize both as-if randomization and departures from
it using just a single sensitivity parameter, \(\Gamma\).

To build intuition for the sensitivity parameter \(\Gamma\), note that
the model in \eqref{eq: indiv sens prob} implies the following
restriction: \begin{equation} \label{eq: odds ratio restrict}
\frac{1}{\Gamma} \leq \frac{\pi_{si}\left(1 - \pi_{sj}\right)}{\pi_{sj}\left(1 - \pi_{si}\right)} \leq \Gamma \text{ for all } i, \, j \, \text{ and } s.
\end{equation} This restriction states that, within any set, no two
units can differ in their odds of treatment by more than a factor of
\(\Gamma\). When \(\Gamma = 1\), all units share the same odds of
treatment, corresponding to as-if randomization. By contrast, larger
values of \(\Gamma\) represent increasingly severe departures from this
assumption.

\citet[pp.~1424--1425]{rosenbaum1995a} shows that the converse also
holds: The restriction in \eqref{eq: odds ratio restrict} implies a
model of the form in \eqref{eq: indiv sens prob}. For any collection of
treatment probabilities satisfying the bound in
\eqref{eq: odds ratio restrict}, it is always possible to find values of
\(u_{si} \in [0,1]\) for all sets \(s\) and units \(i\), along with a
scalar \(\Gamma \geq 1\), such that the two formulations yield the same
probability distribution over assignments in \(\Omega\). In other words,
\eqref{eq: odds ratio restrict} describes a general restriction on
treatment probabilities that does not assume a particular functional
form. The logistic model in \eqref{eq: indiv sens prob}, by contrast,
provides one convenient parametric representation of that general
restriction.

Thus far, we have conducted inference assuming \(\Gamma = 1\), meaning
that all units within a matched set share the same treatment
probability. Under this as-if randomization assumption, tests of sharp
null hypotheses are exactly valid, while tests of weak null hypotheses
are valid in large studies. In both cases, validity means that the
probability of falsely rejecting the null hypothesis does not exceed the
nominal level \(\alpha\).

When we allow departures from as-if randomization, governed by the
sensitivity parameter \(\Gamma \geq 1\), we seek new \(p\)-values that
remain valid in the same sense. The probability of a false rejection
should not exceed \(\alpha\), regardless of the hidden covariate
\(\mathbf{u}\) or the potential outcomes consistent with the null. The
way we ensure this validity, however, differs between the sharp and weak
frameworks, which we consider in turn.

\subsubsection{How Do Inferences under the Sharp Framework Change under
these
Departures?}\label{how-do-inferences-under-the-sharp-framework-change-under-these-departures}

For a sharp null, if the hidden \(\bm{u}\) were known, we could
calculate from \eqref{eq: indiv sens prob} the exact distribution of
assignments consistent with the matched design for any given value of
\(\Gamma \geq 1\). This distribution would provide the correct reference
for computing \(p\)-values under the null. In particular, the upper
one-sided \(p\)-value could be obtained by summing the probabilities of
all assignments whose test statistic under the null is at least as large
as the observed statistic.

In practice, however, \(\bm{u}\) is unknown. Thus, to ensure validity of
our tests, we compute \(p\)-values under the worst-case choice of
\(\bm{u}\) --- the one that makes the \(p\)-value as large as possible.
Rejection under the worst-case choice of \(\bm{u}\) guarantees rejection
under the actual (but hidden) \(\bm{u}\). Consequently, we will not
reject the null more often than we would if the true assignment
probabilities --- governed by the actual but unobserved \(\bm{u}\) ---
were known under the model in \eqref{eq: indiv sens prob}.

\paragraph{Finding the Worst-Case Scenario of Hidden Confounding for
Valid
Inference}\label{finding-the-worst-case-scenario-of-hidden-confounding-for-valid-inference}

Actually finding this worst-case \(\bm{u}\) is difficult. As a first
step, \citet{rosenbaumkrieger1990} show that in the unmatched (i.e., two
sample) case, the vector \(\bm{u}\) that maximizes the \(p\)-value under
any fixed \(\Gamma \geq 1\) must belong to a restricted set of
possibilities, denoted by \(\mathcal{U}_{+}\). Once the subjects are
ordered from the largest to the smallest outcome, all the candidate
vectors in \(\mathcal{U}_{+}\) look the same: a sequence of \(1\)s at
the top followed by \(0\)s below. We do not know \emph{how many} \(1\)s
should precede the \(0\)s, and this number determines which
configuration of \(\bm{u}\) yields the worst-case \(p\)-value. In an
unmatched study, it is straightforward to enumerate all \(n - 1\) such
candidate vectors in \(\mathcal{U}_+\), and then identify which one
yields the largest \(p\)-value for a fixed \(\Gamma \geq 1\).

Unfortunately, in matched designs, the overall worst-case vector
\(\bm{u}\) cannot be obtained by simply stitching together the
worst-case vectors from each matched set. That is, the global worst-case
is not just the collection of local worst-cases. Instead,
\(\mathcal{U}_{+}\) consists of \(\prod_{s = 1}^S (n_s - 1)\) total
candidate vectors for the worst-case \(\bm{u}\) --- a quantity that
quickly becomes infeasible to enumerate directly. For example, with only
\(20\) matched sets of \(4\) units each, the number of candidate vectors
already exceeds \(3.5\) billion.

\subparagraph{Separable Approximation}\label{separable-approximation}

To address this challenge, \citet{gastwirthetal2000} propose a practical
shortcut called the \emph{separable approximation}. The idea is to
select, within each matched set, the configuration \(\bm{u}_s\) (from
the set-specific candidate sequences of 1s and 0s) that maximizes the
expected value of the test statistic in that set under the null. If more
than one candidate yields the same expectation, the choice goes to the
\(\bm{u}_s\) that produces the larger variance of the test statistic in
that set under the null. The method is called ``separable'' because it
then stitches together the choices of \(\bm{u}_s\) made separately
within each matched set, rather than searching over all possible
combinations across sets. The resulting \(\bm{u}\) may not give the
exact worst-case \(p\)-value; yet in designs with many small matched
sets, the error is negligible.

\subparagraph{Taylor Series
Approximation}\label{taylor-series-approximation}

The separable approximation is a useful shortcut, but it can fail in
designs with relatively few matched sets or with highly unbalanced set
sizes. In such cases, the \(\bm{u}\) selected by the separable
approximation may yield \(p\)-values that are smaller than the true
worst-case \(p\)-value. \citet{rosenbaum2018} therefore introduces a
refinement that guarantees valid inference.

The key idea is to reframe hypothesis testing in terms of a function
that, for each configuration of hidden confounding
\(\bm{u} \in \mathcal{U}_{+}\), combines the gap between the null
expectation and the observed test statistic with a corresponding Normal
critical buffer. Concretely, for \(\alpha = 0.05\) and corresponding
critical value \(1.64\), this function is the expected value of the test
statistic under \((\bm{u}, \, \Gamma)\) minus the observed test
statistic, plus \(1.64\) times the standard deviation of the test
statistic under \((\bm{u}, \, \Gamma)\). The function is nonpositive
exactly when the observed test statistic lies at least \(1.64\) standard
deviations above its null expectation, and positive otherwise.
Therefore, the null hypothesis is rejected if and only if this function
is nonpositive.

We can code this function in \texttt{R} as follows.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Rosenbaum (2018) objective: expectation {-} observed + kappa * SD}
\CommentTok{\# Nonpositive values imply rejection at level alpha}
\NormalTok{sens\_objective }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(null\_expect,}
\NormalTok{                           null\_variance,}
\NormalTok{                           obs\_stat,}
                           \AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{) \{}
  \CommentTok{\# null\_expect   : overall null expectation of the test statistic}
  \CommentTok{\# null\_variance : overall null variance of the test statistic}
  \CommentTok{\# obs\_stat      : observed value of the test statistic}
  \CommentTok{\# alpha         : test size (e.g., 0.05 gives kappa about 1.64)}

  \CommentTok{\# Normal critical value}
\NormalTok{  kappa  }\OtherTok{\textless{}{-}} \FunctionTok{qnorm}\NormalTok{(}
    \AttributeTok{p =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha}
\NormalTok{  )}

  \CommentTok{\# Null standard deviation}
\NormalTok{  null\_sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}
\NormalTok{    null\_variance}
\NormalTok{  )}

  \CommentTok{\# Gap between null expectation and observed statistic}
  \CommentTok{\# (null\_expect {-} obs\_stat), + Normal buffer (kappa * null\_sd)}
\NormalTok{  obj\_val }\OtherTok{\textless{}{-}}\NormalTok{ (null\_expect }\SpecialCharTok{{-}}\NormalTok{ obs\_stat) }\SpecialCharTok{+}\NormalTok{ kappa }\SpecialCharTok{*}\NormalTok{ null\_sd}

  \FunctionTok{return}\NormalTok{(obj\_val)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\doublespacing

To build intuition, we next evaluate this function at \(\Gamma = 1\).

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Evaluate under Gamma = 1 using null\_ev, null\_var, and obs\_stat}
\FunctionTok{sens\_objective}\NormalTok{(}
  \AttributeTok{null\_expect   =}\NormalTok{ null\_ev,}
  \AttributeTok{null\_variance =}\NormalTok{ null\_var,}
  \AttributeTok{obs\_stat      =}\NormalTok{ obs\_stat,}
  \AttributeTok{alpha         =} \FloatTok{0.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] -0.06500212
\end{verbatim}

\doublespacing

The resulting value is negative, indicating rejection of the null at the
chosen significance level. This is exactly what we would expect: Because
we previously rejected the sharp null hypothesis that \(\tau_h = 0\) for
all units at \(\Gamma = 1\), the function evaluated at \(\Gamma = 1\) is
indeed nonpositive.

The crucial property of this function is that it is concave over
\(\mathcal{U}_{+}\), which means that a tangent line drawn at \emph{any}
\(\bm{u} \in \mathcal{U}_+\) lies above the function \emph{everywhere}
on \(\mathcal{U}_{+}\). \citet{rosenbaum2018} draws the tangent line at
the configuration of \(\bm{u}\) chosen by the separable approximation.
Because the original function is concave, this tangent line provides a
global upper bound on the function for all candidate configurations of
hidden confounding. If this upper bound is nonpositive, then the
function itself must also be nonpositive. Consequently, rather than
maximizing a curved function over \(\mathcal{U}_{+}\), we can instead
maximize a linear function, which greatly simplifies the optimization.

Straight lines are easy to work with because they decompose additively
across matched sets. We can therefore determine, within each stratum
separately, which hidden-bias pattern makes the tangent line as large as
possible, and then add up these stratum-specific contributions. The
resulting sum is the maximum value of the tangent line over all
\(\bm{u} \in \mathcal{U}_{+}\).

Recalling that the original function is concave, if the maximum value of
the tangent-line approximation over \(\bm{u} \in \mathcal{U}_{+}\) is at
or below zero, then the original function itself must be nonpositive for
every \(\bm{u} \in \mathcal{U}_{+}\). Therefore, we can safely base the
decision to reject the null hypothesis or not on the Taylor
approximation. Although valid, this procedure can be conservative: The
tangent line may remain above zero even when the original function would
be below zero at its true worst-case \(\bm{u}\). By contrast, the
separable approximation can be liberal, as it may reject even when the
worst-case value of the function is positive.

\paragraph{Conducting Worst-Case Sensitivity
Analysis}\label{conducting-worst-case-sensitivity-analysis}

Below we report the upper one-sided \(p\)-value obtained under the
separable approximation, along with an indication of whether the
resulting decision to reject or not reject the null hypothesis agrees
with the decision implied by the Taylor series approximation. Agreement
or disagreement between the two methods is determined by the sign of the
Taylor-series--based bound on the function described above that governs
rejection of the null hypothesis. Disagreement can occur only when the
separable approximation yields a \(p\)-value slightly below \(\alpha\),
indicating rejection, while the Taylor series approximation yields a
positive value, leading to non-rejection.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Grid of Gamma values}
\NormalTok{Gamma\_vals }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}
  \AttributeTok{from =} \DecValTok{1}\NormalTok{,}
  \AttributeTok{to =} \FloatTok{1.5}\NormalTok{,}
  \AttributeTok{by =} \FloatTok{0.0001}
\NormalTok{)}

\CommentTok{\# lapply() runs sensitivity analysis at each Gamma, returns list of results}
\NormalTok{sens\_results }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(}
  \AttributeTok{X =}\NormalTok{ Gamma\_vals,}
  \AttributeTok{FUN =} \ControlFlowTok{function}\NormalTok{(g) \{}
\NormalTok{    out }\OtherTok{\textless{}{-}} \FunctionTok{senstrat}\NormalTok{(}
      \AttributeTok{sc          =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{ldur\_tilde\_hm\_scaled, }\CommentTok{\# outcome}
      \AttributeTok{z           =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{UN,                   }\CommentTok{\# treatment indicator}
      \AttributeTok{st          =}\NormalTok{ data\_matched}\SpecialCharTok{$}\NormalTok{fm,                   }\CommentTok{\# matched set}
      \AttributeTok{gamma       =}\NormalTok{ g,                                 }\CommentTok{\# Gamma}
      \AttributeTok{alternative =} \StringTok{"greater"}\NormalTok{,                         }\CommentTok{\# upper{-}tail test}
      \AttributeTok{detail      =} \ConstantTok{TRUE} \CommentTok{\# return intermediate quantities}
\NormalTok{    )}

    \CommentTok{\# Separable p{-}value}
\NormalTok{    p\_sep }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
\NormalTok{      out}\SpecialCharTok{$}\NormalTok{Separable[}\StringTok{"P{-}value"}\NormalTok{]}
\NormalTok{    )}

    \CommentTok{\# Taylor series margin (cvA)}
\NormalTok{    cvA }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
\NormalTok{      out}\SpecialCharTok{$}\NormalTok{lambda[}\StringTok{"Linear Taylor bound"}\NormalTok{]}
\NormalTok{    )}

    \CommentTok{\# Decisions}
\NormalTok{    sep\_reject }\OtherTok{\textless{}{-}}\NormalTok{ p\_sep }\SpecialCharTok{\textless{}=}\NormalTok{ alpha          }\CommentTok{\# separable rejects?}
\NormalTok{    tay\_reject }\OtherTok{\textless{}{-}}\NormalTok{ cvA }\SpecialCharTok{\textless{}=} \DecValTok{0}                \CommentTok{\# Taylor rejects?}

    \CommentTok{\# Store results for this value of Gamma}
    \FunctionTok{data.frame}\NormalTok{(}
      \AttributeTok{Gamma     =}\NormalTok{ g,        }\CommentTok{\# sensitivity parameter}
      \AttributeTok{p\_sep     =}\NormalTok{ p\_sep,    }\CommentTok{\# separable p{-}value}
      \AttributeTok{cvA       =}\NormalTok{ cvA,      }\CommentTok{\# Taylor bound}
      \AttributeTok{agree\_tay =}\NormalTok{ (sep\_reject }\SpecialCharTok{==}\NormalTok{ tay\_reject) }\CommentTok{\# agreement indicator}
\NormalTok{    )}
\NormalTok{  \}}
\NormalTok{)}

\CommentTok{\# Bind into a single data frame}
\NormalTok{sens\_df }\OtherTok{\textless{}{-}} \FunctionTok{do.call}\NormalTok{(}
  \AttributeTok{what =}\NormalTok{ rbind,}
  \AttributeTok{args =}\NormalTok{ sens\_results}
\NormalTok{)}

\CommentTok{\# Smallest Gamma where the separable p{-}value is \textgreater{}= alpha}
\NormalTok{sens\_value\_sep }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}
\NormalTok{  sens\_df}\SpecialCharTok{$}\NormalTok{Gamma[sens\_df}\SpecialCharTok{$}\NormalTok{p\_sep }\SpecialCharTok{\textgreater{}=}\NormalTok{ alpha]}
\NormalTok{)}

\CommentTok{\# Taylor series sensitivity value:}
\CommentTok{\# smallest Gamma at which Taylor margin becomes positive (non{-}rejection)}
\NormalTok{sens\_value\_tay }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}
\NormalTok{  sens\_df}\SpecialCharTok{$}\NormalTok{Gamma[sens\_df}\SpecialCharTok{$}\NormalTok{cvA }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

For this matched dataset, the conclusions from the separable and Taylor
series approximations agree for nearly all values of \(\Gamma\),
differing over only a narrow interval from 1.1361 to 1.1399. As these
results indicate, we can reject the sharp null of no effect under as-if
randomization (i.e., \(\Gamma = 1\)), but this conclusion is sensitive
to departures from that assumption. Using the more conservative Taylor
series approximation, we can no longer reject the sharp null of no
effect against the alternative of a larger effect at the
\(\alpha = 0.05\) level once \(\Gamma\) reaches approximately 1.14.

The plot below illustrates this comparison and clarifies how the two
approaches relate across values of \(\Gamma\).

\singlespacing
\begin{figure}[H]

{\centering \includegraphics{Building_Design-Based_Matching_Pipeline_files/figure-latex/unnamed-chunk-56-1} 

}

\caption{Sensitivity analysis for the sharp null of no individual treatment effect for all units. The top panel shows upper one-sided $p$-values under the separable approximation across values of $\Gamma$; the bottom panel reports, across the same values of $\Gamma$, the corresponding Taylor series margin, with the zero line marking the rejection boundary. The shaded vertical band highlights values of $\Gamma$ for which the separable approximation and the Taylor series approximation lead to different rejection decisions.}\label{fig:unnamed-chunk-56}
\end{figure}
\doublespacing

Zooming in on the shaded vertical band --- corresponding to values of
\(\Gamma\) for which the two approaches yield different conclusions
(between 1.1361 to 1.1399) --- shows that the two methods diverge in
exactly the way one would expect. Over this range of \(\Gamma\) values,
the Taylor series margin lies just above zero, indicating no rejection
of the sharp null, while the separable approximation yields \(p\)-values
just below \(0.05\), indicating rejection. This pattern reflects the
relative conservatism of the Taylor series approximation: Rejection
under the Taylor series approach implies rejection under the separable
approach, but not vice versa.

Both approaches to sensitivity analysis rely on multiple approximations.
For example, the separable approximation is used to approximate the
worst-case configuration of hidden bias \(\bm{u} \in \mathcal{U}_+\),
and inference additionally relies on a Normal approximation to the null
randomization distribution of the test statistic. If the exact
randomization distribution were used instead, the resulting sensitivity
conclusions could differ for certain values of \(\Gamma\). In principle,
one could also assess sensitivity at a given \(\Gamma\) using the exact
randomization distribution by fixing a configuration of hidden bias
\(\bm{u}\) --- for example, the separable choice --- and deriving, from
\eqref{eq: indiv sens prob}, the implied probability distribution on
\(\Omega\), which can then be combined with the previously defined
\texttt{exact\_sharp\_null\_dist} to compute the corresponding
\(p\)-value.

\subsubsection{How Do Inferences under the Weak Framework Change under
these
Departures?}\label{how-do-inferences-under-the-weak-framework-change-under-these-departures}

Compared to tests of the sharp null hypothesis of no effect,
constructing valid tests of an analogous weak null hypothesis is more
challenging. A sharp null hypothesis specifies all missing potential
outcomes, so we need only consider \(p\)-values over configurations of
\(\bm{u} \in \mathcal{U}_{+}\), rather than also over multiple
configurations of potential outcomes. By contrast, a weak null permits
many possible configurations of potential outcomes, so identifying the
worst-case \(p\)-value requires optimization over both \(\bm{u}\) and
the potential outcomes consistent with the null. This joint optimization
is computationally tractable only in restricted settings, such as those
with binary outcomes \citep{fogartyetal2017} or matched-pair designs
\citep{fogarty2020}.

A more generally applicable approach is proposed by \citet{fogarty2023},
which avoids the need for an explicit search for the worst-case
\(p\)-value over all configurations of \(\bm{u}\) and potential outcomes
consistent with the null hypothesis about \(\tau\). To build intuition
for this approach, note that the following inverse probability weighted
(IPW) version of the Difference-in-Means is unbiased for the ATE,
\(\tau\): \begin{align} \label{eq: weighted diff-in-means}
\sum \limits_{s = 1}^S (n_s/n) \left(\frac{1}{\abs{\Omega_s}}\right)\left(\frac{\hat{\tau}_s}{p(\bm{z}_s)}\right),
\end{align} where \(p(\bm{z}_s)\) denotes the probability of assignment
\(\bm{z}_s\) among all treatment assignments in set \(s\) that hold
fixed the realized number of treated units, with \(\abs{\Omega_s}\)
denoting, as defined earlier, the total number of such assignments. Both
\(\hat{\tau}_s\) and \(p(\bm{z}_s)\) are evaluated at the same realized
treatment assignment \(\bm{z}_s\) within matched set \(s\). In other
words, \(p(\bm{z}_s)\) denotes the probability of the assignment under
which the treated and control outcomes in set \(s\) --- and hence the
Difference-in-Means \(\hat{\tau}_s\) --- aree realized.

When \(\Gamma = 1\), this probability \(p(\bm{z}_s)\) is
\(1/\abs{\Omega_s}\), and the IPW Difference-in-Means reduces to the
usual unweighted Difference-in-Means, \(\hat{\tau}\). When
\(\Gamma > 1\), however, \(p(\bm{z}_s)\) is no longer known exactly. In
matched designs that may include sets with a single treated unit and
many controls as well as sets with a single control unit and many
treated units, \(\Gamma\) restricts the assignment probability to lie
within bounds consistent with the specified degree of departure from
as-if randomization: \begin{align} \label{eq: prob bounds}
\dfrac{1}{\Gamma (n_s - 1) + 1} \leq p(\bm{z}_s) \leq \dfrac{\Gamma}{(n_s - 1) + \Gamma},
\end{align} for all \(\bm{z}_s \in \Omega_s\) and for all matched sets
\(s\).

Since the IPW Difference-in-Means in \eqref{eq: weighted diff-in-means}
cannot be directly computed when \(\Gamma > 1\), \citet{fogarty2023}
instead uses the bounds in \eqref{eq: prob bounds} to construct a
worst-case version of this IPW Difference-in-Means. For tests of a null
hypothesis about the overall ATE across all matched sets, this
worst-case procedure operates on the set-specific Difference-in-Means
centered at the null ATE, \(\hat{\tau}_s - \tau_0\), and applies the
upper bound from \eqref{eq: prob bounds} whenever
\(\hat{\tau}_s \geq \tau_0\) and the lower bound whenever
\(\hat{\tau}_s < \tau_0\). When testing the null against a smaller
alternative, the procedure reverses these substitutions.

To see the value of this procedure, consider testing a null hypothesis
about the ATE against the alternative of a larger ATE.
\citet{fogarty2023} shows that, for any \(\Gamma \geq 1\), the expected
value of this worst-case IPW Difference-in-Means --- defined under
whatever the true distribution on \(\Omega\) consistent with that
\(\Gamma\) happens to be --- is always less than or equal to the null
when it is true. Conversely, when testing against the alternative of a
smaller ATE, this expectation is greater than or equal to the null when
it is true. Importantly, these properties hold for all possible values
of \(\bm{u}\) and all configurations of potential outcomes that are
consistent with the null hypothesis.

How does this property of the expected value ensures a valid test in
sufficiently large studies? Sticking to the case of testing against a
larger ATE, the intuition is straightforward: If the expected value of
the worst-case IPW Difference-in-Means is less than or equal to the null
when it is true, then the worst-case IPW Difference-in-Means tends to
fall at or below the null rather than above it. In other words, the
procedure intentionally ``tilts'' the worst-case IPW Difference-in-Means
in the direction opposite the alternative, making the procedure
conservative.

In addition to this property of the expected value, a second key
ingredient for valid hypothesis testing concerns variance estimation.
For any fixed \(\Gamma \geq 1\), an analogue of the variance estimator
from \citet{fogarty2018} (discussed above) consistently overestimates
(or bounds above) the true variance of the worst-case IPW
Difference-in-Means. As a result, using this variance estimator further
reduces the magnitude of the standardized test statistic --- the
worst-case IPW Difference-in-Means, which is already centered at the
null ATE, divided by the square root of the estimated variance ---
relative to what would be obtained using the true (but unknown)
variance.

Together, these two properties work in the same direction:

\begin{itemize}
\tightlist
\item
  The expected value is at or below the null, keeping the center of the
  distribution at or shifted away from the upper tail, and
\item
  the variance estimate tends to be too large, which pulls the
  standardized statistic closer to zero.
\end{itemize}

As a result, when the null is true, the probability that the
standardized statistic falls in the upper tail of the standard Normal
distribution --- that is, the probability of falsely rejecting the null
--- remains at or below the nominal significance level. Hence, the test
is conservative (valid) in large studies. Analogous reasoning applies
when testing against the alternative of a smaller effect: When the null
hypothesis is true, the probability that the standardized value falls in
the lower tail of the standard Normal distribution also stays at or
below the nominal significance level.

To implement this approach from \citet{fogarty2023}, we first source
from the GitHub repository an \texttt{R} function that, for a fixed
\(\Gamma \geq 1\), computes the worst-case IPW Difference-in-Means for a
single matched set.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the worst\_case\_IPW() function from GitHub repo}
\FunctionTok{source}\NormalTok{(}
  \FunctionTok{paste0}\NormalTok{(}
\NormalTok{    base\_url, }\StringTok{"/R/worst\_case\_IPW.R"}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

We now use this function to calculate the worst-case IPW version of the
Difference-in-Means within each matched set. To form the overall
statistic, we average the set-specific values using weights equal to
each set's contribution to the total number of units. Finally, we center
the worst-case IPW Difference-in-Means by the null ATE, standardize this
difference using the conservative variance estimator from
\citet{fogarty2018}, and compare the resulting standardized test
statistic to the standard Normal distribution to obtain \(p\)-values.

\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# One{-}sided sensitivity analysis for the weak null (ATE = 0)}

\CommentTok{\# Null and alternative for the weak{-}null test}
\NormalTok{null\_ATE    }\OtherTok{\textless{}{-}} \DecValTok{0}                  \CommentTok{\# Null: ATE = 0}

\NormalTok{alternative }\OtherTok{\textless{}{-}} \StringTok{"greater"}          \CommentTok{\# Alt: ATE \textgreater{} 0 (upper{-}tail test)}

\CommentTok{\# Data frame to store results for each Gamma}
\NormalTok{weak\_sens\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Gamma   =}\NormalTok{ Gamma\_vals,}
  \AttributeTok{p\_value =} \ConstantTok{NA\_real\_}
\NormalTok{)}

\ControlFlowTok{for}\NormalTok{ (g }\ControlFlowTok{in}\NormalTok{ Gamma\_vals) \{ }\CommentTok{\# Loop over Gamma values}

  \CommentTok{\# Worst{-}case IPW estimate within each matched set at Gamma = g}
\NormalTok{  set\_stats }\OtherTok{\textless{}{-}}\NormalTok{ data\_matched }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{group\_by}\NormalTok{(}
\NormalTok{      fm}
\NormalTok{    ) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{summarise}\NormalTok{(}
      \AttributeTok{n      =} \FunctionTok{n}\NormalTok{(),                        }\CommentTok{\# Set size n\_s}
      \AttributeTok{weight =}\NormalTok{ n }\SpecialCharTok{/} \FunctionTok{nrow}\NormalTok{(data\_matched),     }\CommentTok{\# Weight n\_s / n}
      \AttributeTok{est    =} \FunctionTok{worst\_case\_IPW}\NormalTok{(             }\CommentTok{\# Worst{-}case IPW in set s}
        \AttributeTok{z           =}\NormalTok{ UN,                  }\CommentTok{\# Treatment indicator}
        \AttributeTok{y           =}\NormalTok{ ldur,                }\CommentTok{\# Outcome}
        \AttributeTok{Gamma       =}\NormalTok{ g,                   }\CommentTok{\# Sensitivity parameter (Gamma)}
        \AttributeTok{tau\_h       =}\NormalTok{ null\_ATE,            }\CommentTok{\# Weak null: ATE = 0}
        \AttributeTok{alternative =}\NormalTok{ alternative          }\CommentTok{\# Direction of alternative}
\NormalTok{      ),}
      \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{    )}

  \CommentTok{\# Overall worst{-}case IPW statistic (weighted average across sets)}
\NormalTok{  wc\_ipw\_stat }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}
\NormalTok{    set\_stats}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{*}\NormalTok{ set\_stats}\SpecialCharTok{$}\NormalTok{est}
\NormalTok{  )}

  \CommentTok{\# Variance estimate for the worst{-}case IPW statistic}
\NormalTok{  var\_hat }\OtherTok{\textless{}{-}} \FunctionTok{fine\_strat\_var\_est}\NormalTok{(}
    \AttributeTok{strat\_ns   =}\NormalTok{ set\_stats}\SpecialCharTok{$}\NormalTok{n,}
    \AttributeTok{strat\_ests =}\NormalTok{ set\_stats}\SpecialCharTok{$}\NormalTok{est}
\NormalTok{  )}

  \CommentTok{\# Standardized worst{-}case IPW statistic, centered at the null}
\NormalTok{  se\_hat   }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}
\NormalTok{    var\_hat}
\NormalTok{  )}

\NormalTok{  std\_stat }\OtherTok{\textless{}{-}}\NormalTok{ (wc\_ipw\_stat }\SpecialCharTok{{-}}\NormalTok{ null\_ATE) }\SpecialCharTok{/}\NormalTok{ se\_hat}

  \CommentTok{\# One{-}sided p{-}value, determined by the alternative}
  \ControlFlowTok{if}\NormalTok{ (alternative }\SpecialCharTok{==} \StringTok{"greater"}\NormalTok{) \{}
    \CommentTok{\# Upper{-}tail test: ATE \textgreater{} 0}
\NormalTok{    p\_val }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{(std\_stat)}
\NormalTok{  \} }\ControlFlowTok{else} \ControlFlowTok{if}\NormalTok{ (alternative }\SpecialCharTok{==} \StringTok{"less"}\NormalTok{) \{}
    \CommentTok{\# Lower{-}tail test: ATE \textless{} 0}
\NormalTok{    p\_val }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(std\_stat)}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Only one{-}sided alternatives (\textasciigrave{}greater\textquotesingle{} or \textasciigrave{}less\textquotesingle{})."}\NormalTok{)}
\NormalTok{  \}}

  \CommentTok{\# Store result for this Gamma}
\NormalTok{  weak\_sens\_df}\SpecialCharTok{$}\NormalTok{p\_value[weak\_sens\_df}\SpecialCharTok{$}\NormalTok{Gamma }\SpecialCharTok{==}\NormalTok{ g] }\OtherTok{\textless{}{-}}\NormalTok{ p\_val}
\NormalTok{\}}

\CommentTok{\# Sensitivity value: smallest Gamma where one{-}sided test no longer rejects}
\NormalTok{weak\_sens\_value }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}
\NormalTok{  weak\_sens\_df}\SpecialCharTok{$}\NormalTok{Gamma[weak\_sens\_df}\SpecialCharTok{$}\NormalTok{p\_value }\SpecialCharTok{\textgreater{}=}\NormalTok{ alpha]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\doublespacing

Below, we plot the upper one-sided \(p\)-values corresponding to
\(\Gamma\) values from 1 to 1.5.

\singlespacing
\begin{figure}[H]

{\centering \includegraphics{Building_Design-Based_Matching_Pipeline_files/figure-latex/unnamed-chunk-59-1} 

}

\caption{One-sided upper $p$-values for the weak null hypothesis of zero average effect across values of the sensitivity parameter $\Gamma$.}\label{fig:unnamed-chunk-59}
\end{figure}
\doublespacing

Under as-if randomization (\(\Gamma = 1\)), we find evidence of a
positive average effect. This conclusion about the weak null is slightly
more robust to departures from as-if randomization than our earlier
rejection of the sharp null of no effect at \(\Gamma = 1\). However, in
absolute terms, the evidence for a positive ATE remains sensitive. Our
qualitative conclusion about the null hypothesis that the ATE equals
zero changes once \(\Gamma\) reaches 1.1756.

It is important to emphasize that this sensitivity analysis guarantees
validity across \emph{all} configurations of potential outcomes
consistent with the weak null. By contrast, \citet{fogarty2023} also
describes an alternative sensitivity analysis that restricts attention
to subsets of configurations that researchers may regard as more
plausible. Such alternatives can produce smaller \(p\)-values, but at
the cost of forfeiting validity for certain (possibly unrealistic)
potential outcome configurations.

\section{Conclusion}\label{conclusion}

We have now completed the full matching pipeline. We began by
constructing matched sets and then conducted inference under the as-if
randomization assumption, treating the matched design as a collection of
completely randomized experiments within blocks. We examined inference
under both sharp and weak null frameworks --- corresponding,
respectively, to unit-level causal effects and average effects --- and
then assessed the sensitivity of these inferences to potential
violations of the as-if randomization assumption. The embedded code,
accompanied by extensive comments and illustrated through the running
example from \citet{gilligansergenti2008}, is intended to be readily
adapted by practitioners to their own datasets.

\subsection{Limitations and Related Topics Beyond Our
Scope}\label{limitations-and-related-topics-beyond-our-scope}

For clarity and focus, we have excluded several important topics, though
we have pointed to relevant references where appropriate. Some of these
omissions are not specific to matching or observational studies. In
particular, we have not addressed imperfect compliance with treatment
assignment, missing outcomes, clustered (rather than individual-level)
assignment, or interference settings in which a subject's outcome
depends on others' treatment assignments.

Our analysis has focused on inference for two causal targets only: a
constant, additive treatment effect and the average treatment effect. We
have not considered alternative effect models, such as dilated effects
\citep{rosenbaum1999}, multiplicative effects, or Tobit effects
\citep[pp.~46--49]{rosenbaum2010}. Throughout, we have treated causal
targets as fixed quantities (over the set of treatment assignments
consistent with the matched design), rather than as random variables. As
a result, we have excluded attributable effects
\citep{rosenbaum2001, rosenbaum2003, hansenbowers2009} and the average
treatment effect on the treated \citep{sekhonshem-tov2021}. We have also
set aside methods for joint inference on sharp and weak causal
hypotheses \citep{ding2017, wuding2021, cohenfogarty2022}, as well as
strategies that improve the power of hypothesis tests by rescaling
outcomes or choosing alternative test statistics, including
regression-assisted approaches
\citep{lin2013, cohenfogarty2023, guobasse2023}.

Several omissions are specific to matching methodology itself:

\begin{itemize}
\item
  First, we have not covered a range of \textbf{alternative matching and
  balancing approaches}, including nonbipartite matching for multivalued
  treatments
  \citep[pp.~207--221]{luetal2001, luetal2011, rosenbaum2010}, template
  matching \citep{silberetal2014}, multilevel matching
  \citep{zubizarretakeele2017, pimenteletal2018}, risk-set matching
  \citep{lietal2001}, cardinality matching \citep{zubizarretaetal2014},
  coarsened exact matching \citep{iacusetal2012}, exterior matching
  \citep{rosenbaumsilber2013}, or generalized full matching
  \citep{savjeetal2021}, among others. We have further assumed that
  researchers specify \emph{ex ante} the set of covariates to be
  balanced, thereby excluding screening procedures that identify
  additional covariates for adjustment based on observed imbalances
  \citep{cochran1965}, as in tapered matching approaches
  \citep{danieletal2008, yuetal2021}. Finally, we have not considered
  balance constraints such as fine and near-fine balance
  \citep{rosenbaumetal2007, yangetal2012, yu2023, pimenteletal2015a, pimenteletal2015b},
  which enforce exact or nearly exact equality of covariate
  distributions.
\item
  Second, we have not discussed the use of \textbf{prognostic
  covariates} identified using pilot or external data. Such approaches
  can substantially improve efficiency by prioritizing covariates that
  strongly predict potential outcomes. For theoretical foundations, see
  \citet{hansen2008a}, with complementary theoretical results and
  practical insights in \citet{salesetal2018}.
\item
  Third, we have considered only matching strategies aimed at justifying
  as-if randomization, not those designed explicitly to improve
  \textbf{design sensitivity} --- that is, robustness to moderate
  violations of as-if randomization \citep[see][Part III,
  pp.~257-311]{rosenbaum2010}. Beyond match construction, researchers
  can also enhance design sensitivity by selecting particular test
  statistics, among other strategies
  \citep{rosenbaum2004, helleretal2009, hsuetal2013, smalletal2013}.
\item
  Fourth, we have excluded \textbf{extensions to covariate balance
  testing} beyond the framework developed in \citet{hansenbowers2008},
  including subsequent contributions by
  \citet{gagnon-bartschshem-tov2019} and \citet{branson2021}, as well as
  related approaches based on the stepwise intersection--union principle
  \citep{hansensales2015}.
\item
  Fifth, we have ignored \textbf{residual imbalance on observed
  covariates}. Specifically, we have proceeded under the assumption that
  matched set membership can justify as-if randomization, even when
  small imbalances remain within matched sets. Under this approach,
  concerns about residual imbalance are absorbed into the sensitivity
  analysis for hidden bias. This approach is not entirely satisfying,
  however, because imbalances on observed covariates are not, in fact,
  hidden. Several methods therefore address such imbalances directly,
  either in approaches targeting individual effects
  \citep{rosenbaum1988, pimentelhuang2024, chenetal2023, hengetal2025}
  or average effects \citep{zhuetal2025}.
\item
  Sixth, we have not incorporated into the overall pipeline an explicit
  approach for defining an \textbf{interpretable study population} in
  matched designs. Common practice excludes units based on limited
  overlap in the estimated propensity score
  \citep{crumpetal2009, kingzeng2006}, but study populations defined in
  this way can be difficult to characterize substantively. Hence,
  alternative approaches define the study population directly in terms
  of a small number of covariates. For example, \citet{traskinsmall2011}
  use a classification tree to define a study population that
  approximates one defined by trimming on the estimated propensity
  score, while \citet{fogartyetal2016} use discrete optimization to
  define a maximal, rectangular region of covariate space with adequate
  overlap on key covariates.
\item
  Seventh, we have not considered \textbf{quasi-experimental devices}
  \citep{campbell1957, campbellstanley1963, shadishetal2002},
  specifically how matched designs can leverage such devices
  \citep[see][Section IV]{rosenbaum2025}. Two prominent
  quasi-experimental devices include an additional control group
  \citep{rosenbaum1987b} and outcomes with known effects
  \citep{rosenbaum1989}, each of which has a range of valuable
  applications. In the context of evidence factors
  \citep{rosenbaum2021}, one use of a second control group is to yield
  stronger causal evidence that is less susceptible to hidden
  confounding \citep{rosenbaum2023b}. For known effects, one
  illustrative use is to support tests for hidden confounding that
  inform sensitivity analyses by ruling out certain violations of as-if
  randomization \citep{rosenbaum2023a}.
\item
  Eighth and finally, we have not addressed settings in which matched
  set membership itself may depend on the treatment assignments --- that
  is, settings with \textbf{\(\bm{Z}\)-dependence}
  \citep{pashleyetal2021, pimentelhuang2024, pimentelyu2024}. Our
  exposition has relied on an analogy to Rubin's framework of
  ``assignment to treatment on the basis of a covariate''
  \citep{rubin1977}, where matched set membership plays the role of the
  covariate. This analogy treats set membership as fixed, but in
  practice membership can be random when the realized treatment
  assignment --- determined prior to matching --- induces the matched
  structure, implying that the structure may vary across possible
  assignments. We have set aside this issue, which may be minor when
  practitioners use sufficiently tight calipers for matching (a point we
  thank Professor Samuel Pimentel for emphasizing in helpful
  discussions).
\end{itemize}

Despite these limitations, the pipeline and design-based perspective
developed here provide a coherent framework for understanding how
matched designs support causal inference. The emphasis on design-based
foundations clarifies the logic underlying the construction of matched
sets and the subsequent steps of inference and sensitivity analysis
under both weak and sharp frameworks. We present this work not as
exhaustive, but as a foundation on which researchers can build when
incorporating more specialized methods tailored to their substantive and
inferential goals.

\newpage

\bibliography{Bibliography.bib}

\end{document}
