##' ---
##' title: "Day 4: Estimation of Average Causal Effects"
##' output: github_document
##' ---
##'
##' This script reproduces every R-generated figure in 2026-06-17.tex and
##' contains, verbatim, every code block shown on the slides.
##'
##' Figures produced here (written to the figures/ subdirectory):
##'   * figures/cra_est_dist_plot.pdf     (estimator's randomization distribution)
##'   * figures/consistency_sim_plot.pdf  (estimator concentrates as N grows)
##' The estimand/estimator diagram, figures/estimator.pdf, is a TikZ figure
##' (see Estimation_Diagram/estimation.tex) -- it is not generated by R.

## ============================================================
## Setup
## ============================================================
## Set saveplots_ <- TRUE to (re)write the figure PDFs the slides include.
if (!exists("saveplots_")) saveplots_ <- FALSE

## If running interactively in RStudio, point R at this file's folder
## (skipped automatically in a non-interactive / Rscript run).
if (interactive() && requireNamespace("rstudioapi", quietly = TRUE) &&
    rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}

library(ggplot2)

## Figures are written to the figures/ subdirectory, which the slides source.
if (saveplots_) dir.create("figures", showWarnings = FALSE)

## The estimator we study all day: treated mean minus control mean.
## z = treatment assignment (1 = treated, 0 = control); y = observed outcome.
diff_in_means <- function(z, y) mean(y[z == 1]) - mean(y[z == 0])

## ============================================================
## 1. Village heads: estimand, unbiasedness, and variance
##    (Gerber and Green 2012, Chapter 2)
## ============================================================

## Potential outcomes are FIXED features of the finite population.
y_c <- c(10, 15, 20, 20, 10, 15, 15)   # y_i(0): control potential outcome
y_t <- c(15, 15, 30, 15, 20, 15, 30)   # y_i(1): treated potential outcome
tau <- y_t - y_c                        # individual effects tau_i = y_i(1) - y_i(0)

N   <- length(y_c)                      # N  = 7 units
n_1 <- 2                                # treated units under complete assignment
n_0 <- N - n_1                          # control units

## Estimand: the finite-population average treatment effect (ATE).
ATE <- mean(tau)                        # = 5 percentage points

## ---- Enumerate the design ----
## Complete random assignment fixes n_1 = 2 treated of N = 7, so there are
## choose(7, 2) = 21 equally likely assignments. Build Omega: each COLUMN is
## one assignment vector z (1 = treated, 0 = control).
Omega <- apply(X = combn(x = N, m = n_1), MARGIN = 2,
               FUN = function(idx) as.integer(1:N %in% idx))
probs <- rep(x = 1 / ncol(Omega), times = ncol(Omega))   # each z equally likely

## For each assignment z, the observed outcome reveals one potential outcome:
##   Y_i = z_i * y_i(1) + (1 - z_i) * y_i(0).
## Apply the difference-in-means to each of the 21 possible data sets.
est_by_assignment <- apply(X = Omega, MARGIN = 2, FUN = function(z) {
  Y <- z * y_t + (1 - z) * y_c
  diff_in_means(z = z, y = Y)
})

## UNBIASEDNESS: averaging the 21 estimates (equal weights) returns the ATE.
sum(est_by_assignment * probs)          # = 5 = ATE

## VARIANCE: average squared distance of the estimator from the ATE.
var_diff_in_means <- sum((est_by_assignment - ATE)^2 * probs)   # ~ 21.19

## ---- Figure: the estimator's randomization distribution ----
cra_df <- data.frame(est = est_by_assignment, prob = probs)
cra_est_dist_plot <- ggplot(data = cra_df, mapping = aes(x = est, y = prob)) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = ATE, linetype = "dashed") +   # centered at the ATE
  xlab(label = "Difference-in-Means") +
  ylab(label = "Probability") +
  theme_bw()

##+ eval=saveplots_
ggsave(plot = cra_est_dist_plot, file = "figures/cra_est_dist_plot.pdf",
       width = 6, height = 4, units = "in", dpi = 300)

##+ eval=TRUE
## ---- Variance from the (here known) potential outcomes ----
## Neyman (1923) form, population-variance convention (divide by N):
pop_var <- function(x) mean((x - mean(x))^2)
sigma2_c <- pop_var(y_c)                                  # ~ 14.29
sigma2_t <- pop_var(y_t)                                  # ~ 42.86
sigma_ct <- mean((y_c - mean(y_c)) * (y_t - mean(y_t)))   # ~  7.14
neyman_var <- (1 / (N - 1)) *
  (n_1 * sigma2_c / n_0 + n_0 * sigma2_t / n_1 + 2 * sigma_ct)   # ~ 21.19

## Imbens and Rubin (2015) form, sample-variance convention (divide by N - 1):
samp_var <- function(x) sum((x - mean(x))^2) / (length(x) - 1)
S2_t   <- samp_var(y_t)      # spread of treated potential outcomes
S2_c   <- samp_var(y_c)      # spread of control potential outcomes
S2_tau <- samp_var(tau)      # spread of individual effects (never observable)
ir_var <- S2_t / n_1 + S2_c / n_0 - S2_tau / N            # ~ 21.19

## All three variance numbers agree (they must):
c(enumerated = var_diff_in_means, neyman = neyman_var, imbens_rubin = ir_var)

## ============================================================
## 2. Consistency: stack copies of the finite population
## ============================================================
## One asymptotic sequence: replicate the 7 villages h times, so
## N = 7h units with n_1 = 2h treated. The ATE and the treated share n_1/N
## stay fixed, so the regularity conditions hold and the estimator concentrates.
##
## The estimator is DISCRETE (finite support). We get its probability mass by:
##   * exact enumeration for small N (h = 1, 2),
##   * Monte Carlo simulation for large N (h = 4, 8).

## Exact probability mass function via full enumeration of the design.
pmf_exact <- function(h) {
  yc <- rep(y_c, h); yt <- rep(y_t, h)
  Nh <- length(yc); n1h <- 2 * h
  cmb <- combn(x = Nh, m = n1h)                 # every choice of treated units
  est <- apply(X = cmb, MARGIN = 2, FUN = function(idx) {
    z <- as.integer(1:Nh %in% idx)
    diff_in_means(z = z, y = z * yt + (1 - z) * yc)
  })
  tab <- as.data.frame(table(round(est, 6)) / length(est))   # mass at each value
  data.frame(est = as.numeric(as.character(tab$Var1)), prob = tab$Freq, N = Nh)
}

## Approximate probability mass function via simulated assignments.
pmf_sim <- function(h, B = 1e5) {
  yc <- rep(y_c, h); yt <- rep(y_t, h)
  Nh <- length(yc); n1h <- 2 * h
  est <- replicate(n = B, expr = {
    z <- sample(rep(c(1, 0), c(n1h, Nh - n1h)))   # one complete random assignment
    diff_in_means(z = z, y = z * yt + (1 - z) * yc)
  })
  tab <- as.data.frame(table(round(est, 6)) / B)
  data.frame(est = as.numeric(as.character(tab$Var1)), prob = tab$Freq, N = Nh)
}

set.seed(seed = 12345)
consist_df <- rbind(pmf_exact(1), pmf_exact(2), pmf_sim(4), pmf_sim(8))
consist_df$panel <- factor(paste0("N = ", consist_df$N),
                           levels = paste0("N = ", 7 * c(1, 2, 4, 8)))

## ---- Figure: discrete distribution tightens on the ATE as N grows ----
## Same x-axis across panels (so the concentration is visible), but FREE y-axes
## (heights stay comparable). No y-axis label: the point is just that the
## estimator concentrates around the ATE.
consistency_sim_plot <- ggplot(data = consist_df, mapping = aes(x = est, y = prob)) +
  geom_segment(aes(xend = est, yend = 0), colour = "grey45", linewidth = 0.35) +
  geom_point(colour = "grey25", size = 0.45) +
  geom_vline(xintercept = ATE, linetype = "dashed") +
  facet_wrap(facets = ~ panel, nrow = 1, scales = "free_y") +
  coord_cartesian(xlim = c(-12, 22)) +
  xlab(label = "Difference-in-Means estimate") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y  = element_blank(),
        axis.ticks.y = element_blank())

##+ eval=saveplots_
ggsave(plot = consistency_sim_plot, file = "figures/consistency_sim_plot.pdf",
       width = 8, height = 2.6, units = "in", dpi = 300)

## ============================================================
## 3. ACORN in R: the estimate                 (slide code, verbatim)
## ============================================================
##+ eval=TRUE

# ACORN GOTV experiment: 28 precincts, complete random assignment
acorn  <- read.csv("acorn03.csv")
z_obs  <- acorn$z           # 1 = canvassed (GOTV), 0 = control
y_obs  <- acorn$vote03      # observed 2003 turnout proportion
N  <- length(z_obs); n1 <- sum(z_obs); n0 <- N - n1   # 28, 14, 14

# Difference-in-Means estimator of the ATE: treated mean - control mean
diff_in_means <- function(z, y) mean(y[z == 1]) - mean(y[z == 0])
tau_hat <- diff_in_means(z = z_obs, y = y_obs)   # ~ 0.036 (about 3.6 points)

## ============================================================
## 4. ACORN in R: exact moments vs. simulation  (slide code, verbatim)
## ============================================================

# Sharp null of no effect => y is FIXED; only the assignment is random.
# |Omega| = choose(28, 14) = 40,116,600 assignments: too many to enumerate,
# so compare EXACT design-based formulas with a Monte Carlo approximation.
ybar <- mean(y_obs)
Sy2  <- sum((y_obs - ybar)^2) / (N - 1)       # finite-population variance
E_treated_exact <- ybar                       # E[treated mean] = grand mean
Var_D_exact     <- Sy2 * (1/n1 + 1/n0)        # exact Var[diff-in-means]

set.seed(seed = 12345)                        # Monte Carlo over assignments
D <- replicate(n = 10^4, expr = diff_in_means(z = sample(x = z_obs), y = y_obs))
mean(D)   # ~ 0        : matches E[diff-in-means] = 0
var(D)    # ~ 0.00062  : matches Var_D_exact
